- core/src/main/scala/doobie/hi/resultset.scala
- core/src/main/scala/doobie/util/query.scala
This provides `sql"blah".query[Woozle].option` as suggested by @prange
> Option combinator for Query; fixes #46

- build.sbt
- contrib/hikari/build.sbt
- contrib/hikari/src/main/scala/doobie/contrib/hikari/HikariTransactor.scala
- example/src/main/scala/example/HikariExample.scala
This implementation is slightly weak because it gives you direct access to the `HikariDataSource` if you ask to configure, but it's good enough for now.
> Hikari transactor and example

- core/src/test/scala/doobie/util/catchable.scala
- core/src/test/scala/doobie/util/catchsql.scala
Filled out remaining tests for `CatchSql` combinators. This fixes #62.
> Finish up core tests

- contrib/h2/src/main/scala/doobie/contrib/h2/h2types.scala
- contrib/h2/src/test/scala/doobie/contrib/h2/h2types.scala
Improved H2 tests. Fixed NPE in array handling.
> In/Out tests for H2

- doc/src/main/tut/01-Introduction.md
- doc/src/main/tut/04-Selecting.md
- doc/src/main/tut/07-Updating.md
- doc/src/main/tut/08-Error-Handling.md
- doc/src/main/tut/10-Custom-Mappings.md
sanity check for docs. they're not perfect but are good enough to tag
> minor edits

- core/build.sbt
> scalaz 7.1.1, scalaz-stream 0.6a

- .travis.yml
> travis gitter hook

- core/src/main/scala/doobie/util/yolo.scala
- core/src/test/scala/doobie/util/yolo.scala
> Yolo mode for Query, Update, Update0

- contrib/h2/src/test/scala/doobie/contrib/h2/h2types.scala
- contrib/postgresql/src/test/scala/doobie/contrib/postgresql/pgtypes.scala
- core/src/main/scala/doobie/util/atom.scala
Adds support for `scalaz.Maybe` for nullable types.
fixes #43
> Atom for Maybe

- core/src/main/scala/doobie/util/composite.scala
small step towards #99 :) This will make possible to derive Composite for HList
> Composite instances for HList and HNil

- core/src/main/scala/doobie/util/transactor.scala
> DataSourceTransactor

- README.md
* fix postgresql.org link
* fix artifact-id from contrib-packages
----
very nice library!
> small README.md fixes

- core/src/main/scala/doobie/imports.scala
- doc/src/main/tut/12-Managing-Connections.md
> Connect doc

- example/src/main/scala/example/PostgresNotify.scala
This doesn't really address any outstanding issues, but is interesting.
> PGNotify example

- core/src/main/scala/doobie/util/composite.scala
`Composite` for any type isomorphic to `HList`. more general (and preferred) version of `ProductTypeClass` instance
> Composite instance for Generic

- contrib/postgresql/src/main/scala/doobie/contrib/postgresql/free/copyin.scala
- contrib/postgresql/src/main/scala/doobie/contrib/postgresql/free/copymanager.scala
- contrib/postgresql/src/main/scala/doobie/contrib/postgresql/free/copyout.scala
- contrib/postgresql/src/main/scala/doobie/contrib/postgresql/free/fastpath.scala
- contrib/postgresql/src/main/scala/doobie/contrib/postgresql/free/largeobject.scala
- contrib/postgresql/src/main/scala/doobie/contrib/postgresql/free/largeobjectmanager.scala
- contrib/postgresql/src/main/scala/doobie/contrib/postgresql/free/pgconnection.scala
- contrib/postgresql/src/main/scala/doobie/contrib/postgresql/hi/connection.scala
- contrib/postgresql/src/main/scala/doobie/contrib/postgresql/hi/largeobject.scala
- contrib/postgresql/src/main/scala/doobie/contrib/postgresql/hi/largeobjectmanager.scala
- contrib/postgresql/src/main/scala/doobie/contrib/postgresql/hi/pgconnection.scala
- contrib/postgresql/src/main/scala/doobie/contrib/postgresql/imports.scala
- contrib/postgresql/src/test/scala/doobie/contrib/postgresql/pgcopy.scala
- contrib/postgresql/src/test/scala/doobie/contrib/postgresql/pglargeobject.scala
- contrib/postgresql/src/test/scala/doobie/contrib/postgresql/pgnotify.scala
- core/src/main/scala/doobie/util/io.scala
- doc/src/main/tut/00-Index.md
- doc/src/main/tut/13-Extensions-PostgreSQL.md
- example/src/main/scala/example/PostgresLargeObject.scala
- example/src/main/scala/example/PostgresNotify.scala
- example/src/main/scala/example/PostgresPoint.scala
> Algebras and free monads for PGConnection and related types

- contrib/postgresql/build.sbt
- contrib/postgresql/src/test/scala/doobie/contrib/postgresql/pglargeobject.scala
- doc/src/main/tut/13-Extensions-PostgreSQL.md
> Update postgres driver to 9.4

- core/src/main/scala/doobie/imports.scala
- doc/src/main/tut/13-Extensions-PostgreSQL.md
> Pg error doc

- core/build.sbt
> scalaz-stream 0.7a

- contrib/specs2/build.sbt
- contrib/specs2/src/main/scala/doobie/contrib/specs2/specs2.scala
- sbt
I haven't executed any code, just made it compile for 3.6.
> Updated to 3.6

- build.sbt
Minor changes following after #171 ... `ctut` should be defined only in `doc`, and there's no point including `bench` and `doc` in the scaladoc.
> remove bench,docs from unidoc; make ctut defined only in doc

- core/src/main/scala/doobie/hi/resultset.scala
- core/src/main/scala/doobie/util/query.scala
> more generalized function for collecting result into some data structure

- .gitignore
- build.sbt
- project/plugins.sbt
- version.sbt
Ok this is an attempt to set up sonatype publishing. A snapshot publish from this branch seemed to work, so we'll see if it shows up on central. Assuming this works, it resolves #194
> bintray to sonatype

- core/src/main/scala/doobie/free/blob.scala
- core/src/main/scala/doobie/free/callablestatement.scala
- core/src/main/scala/doobie/free/clob.scala
- core/src/main/scala/doobie/free/connection.scala
- core/src/main/scala/doobie/free/databasemetadata.scala
- core/src/main/scala/doobie/free/driver.scala
- core/src/main/scala/doobie/free/nclob.scala
- core/src/main/scala/doobie/free/preparedstatement.scala
- core/src/main/scala/doobie/free/ref.scala
- core/src/main/scala/doobie/free/resultset.scala
- core/src/main/scala/doobie/free/sqldata.scala
- core/src/main/scala/doobie/free/sqlinput.scala
- core/src/main/scala/doobie/free/sqloutput.scala
- core/src/main/scala/doobie/free/statement.scala
- doc/src/main/tut/03-Connecting.md
- project/FreeGen.scala
This PR adds `FooIO ~> Kleisli[M, Foo, ?]` and `Foo => FooIO ~> M` to each `free` module, which resolves #195.
> added natural transformations

- doc/src/main/tut/01-Introduction.md
- doc/src/main/tut/03-Connecting.md
- doc/src/main/tut/04-Selecting.md
- doc/src/main/tut/05-Parameterized.md
- doc/src/main/tut/06-Checking.md
- doc/src/main/tut/07-Updating.md
- doc/src/main/tut/08-Error-Handling.md
- doc/src/main/tut/09-Arrays.md
- doc/src/main/tut/10-Custom-Mappings.md
- doc/src/main/tut/11-Unit-Testing.md
- doc/src/main/tut/12-Managing-Connections.md
- doc/src/main/tut/13-Extensions-PostgreSQL.md
- doc/src/main/tut/14-Extensions-H2.md
> minor updates to take advantage of new formatting in tut 0.4.0

- core/src/main/scala/doobie/syntax/string.scala
- core/src/main/scala/doobie/util/query.scala
fixed links. need to do this everywhere, but in any case this resolves #201 (again)
> update links for string/query

- core/src/main/scala/doobie/syntax/string.scala
- core/src/main/scala/doobie/util/composite.scala
> improved implicit not found message

- doc/src/main/tut/07-Updating.md
Adds doc explaining vendor differences re: `withUniqueGeneratedKeys`. resolves #225
> update doc for withUniqueGeneratedKeys

- doc/src/main/tut/15-FAQ.md
> add faq about type ascription

- build.sbt
> change exclude for postgis dep

- core/src/main/scala/doobie/util/meta.scala
- core/src/test/scala/doobie/util/meta.scala
> Meta derivation for unary products

- doc/src/main/tut/01-Introduction.md
- doc/src/main/tut/02-Toolkit.md
- doc/src/main/tut/03-Connecting.md
- doc/src/main/tut/04-Selecting.md
- doc/src/main/tut/05-Parameterized.md
- doc/src/main/tut/13-Extensions-PostgreSQL.md
Odds and ends for 0.2.3
Resolves #242
> minor book updates

- CHANGELOG.md
> Correct the scala version for 0.2.3

- build.sbt
- core/src/main/scala/doobie/util/process.scala
This back-ports the streams upgrade from series/0.3.x
> back-port upgrade to scalaz-stream 0.8

- contrib/postgresql/src/main/scala/doobie/contrib/postgresql/pgtypes.scala
- contrib/postgresql/src/test/scala/doobie/contrib/postgresql/pgtypes.scala
> Add support for UUID array

- contrib/hikari/src/main/scala/doobie/contrib/hikari/HikariTransactor.scala
- contrib/postgresql/src/main/scala/doobie/contrib/postgresql/pgtypes.scala
- contrib/postgresql/src/test/scala/doobie/contrib/postgresql/pgtypes.scala
This pulls late updates in 0.2.x up to 0.3.x
> forward-port uuid arrays and hikari xa ctor

- .travis.yml
- README.md
- build.sbt
- modules/core/src/main/scala/doobie/util/transactor.scala
- project/plugins.sbt
Travis is crapping out on series/0.3.x which is preventing merging of a couple PRs. Trying to get it working here. resolves #301 #306 #307 
Many Updates:
- Scala 2.12.0-M4
- ScalaCheck 1.13.1
- Specs2 3.8.4
- Kind-Projector 0.8.0
- Scalaz 7.2.4
- Scalaz-Stream 0.8.2a
- Shapeless 2.3.1
- tut 0.4.3
> Update to 2.12.0-M4/5 and get build to be reliable, merge minor PRs

- .travis.yml
- project/travis-before-build.sh
- project/travis-build.sh
- yax/core/src/main/scala/doobie/hi/connection.scala
- yax/core/src/main/scala/doobie/hi/resultset.scala
- yax/postgres/src/test/scala/doobie/postgres/manyrows.scala
(NOTE: It's based upon #318)
This PR fixes two issues:
- `doobie.hi.resultset.getNextChunk` ignores given chunk size
- [The entire ResultSet is loaded at once](https://jdbc.postgresql.org/documentation/94/query.html#query-with-cursor)
> Fix #316 - OutOfMemoryError when fetching data from large tables

- yax/docs/src/main/tut/15-FAQ.md
> Add logging and timing related FAQs

- README.md
> Fix wrong url doobie-book of Cats support in README.md

- yax/core/src/main/scala/doobie/util/query.scala
- yax/core/src/test/scala/doobie/util/query.scala
resolves #340 … pardon the whitespace edits
> add Query0 ctor

- build.sbt
- yax/scalatest/src/main/scala/doobie/scalatest/QueryChecker.scala
Ok this undoes #366, which undid #361, which subsumed WIP #331. I think we're good now.
Apologies again to @KadekM and @Milyardo for the confusion.
Resolves #350
> Scalatest (one more time)

- build.sbt
- yax/docs/src/main/tut/13-Extensions-PostgreSQL.md
- yax/postgres/src/main/scala/doobie/postgres/pgistypes.scala
- yax/postgres/src/main/scala/doobie/postgres/pgtypes.scala
- yax/postgres/src/test/scala/doobie/postgres/pgtypes.scala
Addresses #357 by separating postgis stuff into new object.
> separate postgis via provided

- build.sbt
Several mixups here, oops. Fixes #385
> fix publishing of test artifacts

- yax/bench/src/main/scala/doobie/bench/bench.scala
- yax/core/src/main/scala/doobie/imports.scala
- yax/core/src/main/scala/doobie/util/composite.scala
- yax/core/src/main/scala/doobie/util/fragment.scala
- yax/core/src/main/scala/doobie/util/log.scala
- yax/core/src/main/scala/doobie/util/query.scala
- yax/core/src/main/scala/doobie/util/update.scala
- yax/core/src/test/scala/doobie/util/log.scala
- yax/docs/src/main/tut/10-Logging.md
- yax/docs/src/main/tut/11-Arrays.md
- yax/docs/src/main/tut/12-Custom-Mappings.md
- yax/docs/src/main/tut/13-Unit-Testing.md
- yax/docs/src/main/tut/14-Managing-Connections.md
- yax/docs/src/main/tut/15-Extensions-PostgreSQL.md
- yax/docs/src/main/tut/16-Extensions-H2.md
- yax/docs/src/main/tut/17-FAQ.md
This subsumes #354 … the fragments stuff required a different approach to argument handling.
Resolves #292
> Simple Logging

- build.sbt
- yax/core/src/main/scala/doobie/imports.scala
- yax/core/src/main/scala/doobie/syntax/string.scala
- yax/core/src/main/scala/doobie/util/fragment.scala
- yax/core/src/main/scala/doobie/util/pos.scala
- yax/core/src/main/scala/doobie/util/query.scala
- yax/core/src/main/scala/doobie/util/update.scala
- yax/scalatest/src/main/scala/doobie/scalatest/QueryChecker.scala
- yax/specs2/src/main/scala/doobie/specs2/specs2.scala
> use compile-time source positions for query checker

- yax/core/src/main/scala/doobie/util/fragment.scala
- yax/core/src/main/scala/doobie/util/query.scala
- yax/core/src/main/scala/doobie/util/update.scala
- yax/core/src/test/scala/doobie/util/fragment.scala
May want to add some more stuff but getting back to `Fragment` is the trick.
resolves #416
> Add toFragment methods on Query/0 and Update/0

- build.sbt
> add managed sources to packageSrc

- build.sbt
- yax/docs/src/main/tut/09-Error-Handling.md
- yax/docs/src/main/tut/11-Arrays.md
- yax/docs/src/main/tut/14-Managing-Connections.md
- yax/docs/src/main/tut/15-Extensions-PostgreSQL.md
- yax/docs/src/main/tut/16-Extensions-H2.md
- yax/docs/src/main/tut/17-FAQ.md
- yax/example/src/main/scala/example/AnalysisTest.scala
- yax/example/src/main/scala/example/HikariExample.scala
- yax/example/src/main/scala/example/PostgresNotify.scala
- yax/example/src/main/scala/example/PostgresPoint.scala
- yax/h2/src/main/scala/doobie/h2/h2types.scala
- yax/h2/src/main/scala/doobie/h2/imports.scala
- yax/h2/src/main/scala/doobie/h2/package.scala
- yax/h2/src/test/scala/doobie/h2/h2types.scala
- yax/hikari/src/main/scala/doobie/hikari/imports.scala
- yax/postgres/src/main/scala/doobie/postgres/hi/connection.scala
- yax/postgres/src/main/scala/doobie/postgres/hi/pgconnection.scala
- yax/postgres/src/main/scala/doobie/postgres/imports.scala
- yax/postgres/src/main/scala/doobie/postgres/package.scala
- yax/postgres/src/main/scala/doobie/postgres/pgtypes.scala
- yax/postgres/src/main/scala/doobie/postgres/syntax.scala
- yax/postgres/src/test/scala/doobie/postgres/pgtypes.scala
- yax/postgres/src/test/scala/doobie/postgres/unapply.scala
- yax/scalatest/src/main/scala/doobie/scalatest/imports.scala
- yax/specs2/src/main/scala/doobie/specs2/imports.scala
This sets things up so `import doobie.<module>.imports._` will tend to do what you want.
resolves #279
> consistent imports

- yax/docs/src/main/tut/08-Fragments.md
- yax/docs/src/main/tut/10-Logging.md
Wee improvements for fragment and logging chapters.
> doc updates

- yax/core/src/main/scala/doobie/hi/resultset.scala
- yax/docs/src/main/tut/17-FAQ.md
> chunkstyle

- yax/postgres/src/main/scala/doobie/postgres/pgtypes.scala
> fix 'String is not coercible to VARCHAR' problem

- CHANGELOG.md
prompted by
https://twitter.com/francoeurdavid/status/821495869333704704
> breakage note in changelog

- CHANGELOG.md
- yax/core/src/main/scala/doobie/util/fragments.scala
- Added fragments combinators for set.
> Added set and setOpt combinators

- build.sbt
Removed duplication in lib versions in build. Resolves #474
> organize versions

- CHANGELOG.md
- yax/core/src/main/scala/doobie/util/atom.scala
- yax/core/src/main/scala/doobie/util/meta.scala
- yax/core/src/test/scala/doobie/util/composite.scala
- yax/core/src/test/scala/doobie/util/meta.scala
- yax/docs/src/main/tut/11-Arrays.md
- yax/docs/src/main/tut/12-Custom-Mappings.md
- yax/docs/src/main/tut/15-Extensions-PostgreSQL.md
- yax/docs/src/main/tut/17-FAQ.md
- yax/example/src/main/scala/example/PostgresPoint.scala
- yax/postgres/src/main/scala/doobie/postgres/pgistypes.scala
This resolves #462 and related complaints.
Before merging:
> coyoneda for column reads

- README.md
Github did not render the image links
> Fixes image links in readme

- yax/postgres/src/main/scala/doobie/postgres/pgtypes.scala
- yax/postgres/src/test/scala/doobie/postgres/check.scala
Fixes #489 … #431 fixed the write side of the coin, this does the same thing for read.
> fix for 489

- yax/core/src/main/scala/doobie/util/update.scala
- yax/core/src/test/scala/doobie/util/log.scala
This is a branch from #476 that adds tests.
> WIP: update logging

- CHANGELOG.md
- build.sbt
- yax/example/src/test/scala/doobie/AnalysisTestSpecs2BeforeAll.scala
- yax/specs2/src/main/scala/doobie/specs2/specs2.scala
- yax/specs2/src/test/scala/doobie/specs2/beforeall.scala
Rebases #458, adds changlog entries
Fixes #454
> Fix execution flow for AnalysisSpec checks

- yax/docs/src/main/tut/06-Checking.md
- yax/docs/src/main/tut/09-Error-Handling.md
- yax/docs/src/main/tut/11-Arrays.md
- yax/docs/src/main/tut/12-Custom-Mappings.md
- yax/docs/src/main/tut/15-Extensions-PostgreSQL.md
- yax/docs/src/main/tut/16-Extensions-H2.md
- yax/example/src/main/scala/example/PostgresNotify.scala
> Remove 'contrib-' in artifact names

- yax/postgres/src/main/scala/doobie/postgres/syntax.scala
- yax/postgres/src/test/scala/doobie/postgres/syntax.scala
> make pg handler args by-name

- yax/docs/src/main/tut/13-Unit-Testing.md
If there is a better way to do this, feel free to close the PR.
> Add scalaz and cats flags for the unit testing documentation

- yax/core/src/main/scala/doobie/hi/preparedstatement.scala
- yax/core/src/test/scala/doobie/issue/262.scala
> Add handler for null metadata

- CHANGELOG.md
- project/travis-before-build.sh
- yax/docs/src/main/tut/15-Extensions-PostgreSQL.md
- yax/postgres/src/main/scala/doobie/postgres/pgtypes.scala
- yax/postgres/src/test/scala/doobie/postgres/pgtypes.scala
Resolves #419
This adds a mapping for PG `hstore`.
> pg hstore <-> Map[String,String]

- CHANGELOG.md
- yax/docs/src/main/tut/15-Extensions-PostgreSQL.md
- yax/postgres/src/main/scala/doobie/postgres/pgtypes.scala
- yax/postgres/src/test/scala/doobie/postgres/check.scala
- yax/postgres/src/test/scala/doobie/postgres/pgtypes.scala
> Postgres enum can actually have a valid Meta instance

- CHANGELOG.md
- yax/specs2/src/main/scala/doobie/specs2/imports.scala
- yax/specs2/src/main/scala/doobie/specs2/specs2.scala
- yax/specs2/src/test/scala/doobie/specs2/CheckerTests.scala
> generalize analysisspec

- CHANGELOG.md
- yax/core/src/main/scala/doobie/enum/jdbctype.scala
- yax/core/src/main/scala/doobie/hi/preparedstatement.scala
- yax/core/src/main/scala/doobie/util/meta.scala
> add Unknown JdbcType

- yax/example/src/main/scala/example/StreamingCopy.scala
This adds an example with a combinator that demonstrates streaming from one database to another. Resolves #543
> add streaming copy example

- yax/docs/src/main/tut/17-FAQ.md
> Add note about IDE freakouts

- CHANGELOG.md
- build.sbt
Saw the chat on Gitter, simple PR to help.
> Update Specs2 to 3.9.4

- yax/example/src/main/scala/example/OtherSchema.scala
Need to see if this works in general. May be able to make this the default.
> pg schema workaround

- build.sbt
Removes `-Xlint` from `console`.
> make repl not horrible

- yax/core/src/main/scala/doobie/util/transactor.scala
- yax/docs/src/main/tut/14-Managing-Connections.md
> minimal doc on customizing xa

- CHANGELOG.md
- modules/core/src/main/scala/doobie/util/composite.scala
- modules/core/src/main/scala/doobie/util/kernel.scala
- modules/core/src/test/scala/doobie/util/composite.scala
- modules/example/src/main/scala/example/Join.scala
This moves #540 to series/0.5.x.
> option composite

- modules/docs/src/main/tut/docs/01-Introduction.md
Once 0.5.x is merged into master this will have to be changed again ☺️
> Point to branch 0.5.x in the curl call

- .travis.yml
- build.sbt
- modules/core/src/main/scala/doobie/hi/connection.scala
- modules/core/src/main/scala/doobie/syntax/stream.scala
- modules/core/src/main/scala/doobie/util/composite.scala
- modules/core/src/main/scala/doobie/util/kernel.scala
- modules/core/src/main/scala/doobie/util/query.scala
- modules/core/src/main/scala/doobie/util/stream.scala
- modules/core/src/main/scala/doobie/util/update.scala
- modules/example/src/main/scala/example/FreeUsage.scala
- project/travis-build.sh
> WIP - Cats 1.0.0 RC1

- modules/docs/src/main/tut/docs/01-Introduction.md
- modules/docs/src/main/tut/index.md
> Add info on partial unification in key places

- modules/docs/src/main/tut/docs/17-FAQ.md
FAQ for how to type check domains with check constraints. Resolves https://github.com/tpolecat/doobie/issues/641
> FAQ on Typechecking w/ Domains w/Check Constraints

- modules/core/src/main/scala/doobie/util/transactor.scala
- modules/docs/src/main/tut/docs/14-Managing-Connections.md
- modules/docs/src/main/tut/docs/16-Extensions-H2.md
- modules/example/src/main/scala/example/HikariExample.scala
- modules/h2/src/main/scala/doobie/h2/H2Transactor.scala
- modules/h2/src/main/scala/doobie/h2/syntax/h2transactor.scala
- modules/hikari/src/main/scala/doobie/hikari/HikariTransactor.scala
- modules/hikari/src/main/scala/doobie/hikari/syntax/hikaritransactor.scala
- modules/specs2/src/test/scala/doobie/specs2/beforeall.scala
- add streaming constructors
- rename effectful constructors to clarify usage
> transactor updates

- build.sbt
- modules/postgres/src/main/scala/doobie/postgres/hi/aliases.scala
- modules/postgres/src/main/scala/doobie/postgres/hi/lostreaming.scala
- modules/postgres/src/test/scala/doobie/postgres/lostreaming.scala
Provides functions for working with `LargeObject` using fs2.
I'll add an example later (can do it in another PR).
> postgres large object streaming with fs2

- modules/core/src/main/scala/doobie/util/fragment.scala
- modules/core/src/test/scala/doobie/util/fragment.scala
provides stripMargin to `fr` and `sql` string interpolator for parity with standard string interpolators
> adding stripMargin to Fragment

- build.sbt
- cats 1.1.0
- circe 0.9.2
- postgres 42.2.2
> library updates

- .travis.yml
- modules/core/src/main/scala/doobie/util/fragment.scala
- modules/example/src/main/scala/example/Dynamic.scala
- project/travis-build.sh
This provides a way to intercept the statement handler for a fragment and do whatever you like.
Resolves #710
> add Fragment.execWith for custom handling

- modules/docs/src/main/tut/migration.md
- project/travis-build.sh
Adds a few more notes to the migration guide. I think it's mostly fine. 
resolves #614
> update migration guide

- modules/docs/src/main/tut/docs/14-Managing-Connections.md
- modules/docs/src/main/tut/docs/15-Extensions-PostgreSQL.md
> fix old catchable references

- modules/example/src/main/scala/example/Orm.scala
This adds a super super simple ORM example because people keep asking if it's possible. It is, in simple cases like this.
> simple orm

- README.md
> Use https link for microsite

- modules/core/src/main/scala/doobie/util/query.scala
- modules/core/src/main/scala/doobie/util/update.scala
Better #742 per @nigredo-tori's suggestions.
> remove boilerplate in log handling

- build.sbt
fs2-scodec has been folded into fs2 as of 1.0.0-RC3
> remove fs2-scodec

- .travis.yml
- build.sbt
Update the minor of scala 2.12, patch of postgres driver and minor cats.
> Update postgres, scala to 2.12.7 and cats 

- modules/postgres/src/main/scala/doobie/postgres/Instances.scala
- modules/postgres/src/test/scala/doobie/postgres/pgtypes.scala
Adding support for Array[BigDecimal] with Postgres. 
Thank you.
> Support for Array[BigDecimal] with Postgres

- modules/docs/src/main/tut/docs/15-Extensions-PostgreSQL.md
Note: The groupId has changed, the package name inside is still
org.postgis
> Postgis dependency version update

- modules/postgres/src/main/scala/doobie/postgres/Instances.scala
- modules/postgres/src/test/scala/doobie/postgres/pgtypes.scala
Following-up on #839 
thank you
> Bigdecimal array lifted

- .travis.yml
- build.sbt
2.13.0-M5 Support In Place
Currently having an issue with the PostGIS build
> 2.13.0 Support

- modules/example/src/main/scala/example/PostgresNotify.scala
> modernize NOTIFY example

- build.sbt
My CI Success - https://travis-ci.org/ChristopherDavenport/doobie/builds/569550426
> Fix For Broken Build

- modules/core/src/main/scala/doobie/syntax/all.scala
- modules/core/src/main/scala/doobie/syntax/put.scala
- modules/core/src/test/scala/doobie/syntax/put.scala
Not sure if I need to put that Copyright stuff at the top or if it would be autogenerated anyways.
Also this is my first "big" PR so be gentle :)
> Added syntax for converting to a fragment

- .travis.yml
- CHANGELOG.md
- build.sbt
- modules/docs/src/main/tut/docs/17-Quill.md
This kind of fixes doc generation. The license and changelog aren't appearing for some reason.
> doc site updates

- .travis.yml
- modules/core/src/main/scala/doobie/util/fragments.scala
- modules/core/src/main/scala/doobie/util/query.scala
- modules/core/src/main/scala/doobie/util/update.scala
- modules/core/src/main/scala/doobie/util/write.scala
- modules/core/src/test/scala/doobie/util/fragments.scala
- modules/core/src/test/scala/doobie/util/query.scala
> Backport 1037

- modules/core/src/main/scala/doobie/enum/jdbctype.scala
- modules/core/src/main/scala/doobie/util/meta.scala
- modules/docs/src/main/tut/docs/12-Custom-Mappings.md
- modules/h2/src/test/scala/doobie/h2/h2types.scala
- modules/postgres/src/test/scala/doobie/postgres/pgtypes.scala
> Add new Meta instances and tests for JSR-310 data types

- build.sbt
- modules/core/src/test/scala/doobie/util/arbitraries/SQLArbitraries.scala
- modules/core/src/test/scala/doobie/util/arbitraries/StringArbitraries.scala
- modules/core/src/test/scala/doobie/util/arbitraries/TimeArbitraries.scala
- modules/h2/src/test/scala/doobie/h2/h2types.scala
- modules/postgres/src/test/scala/doobie/postgres/pgtypes.scala
> Property-based testing for Pg and H2

- build.sbt
- modules/core/src/main/scala/doobie/util/fragments.scala
- modules/core/src/test/scala/doobie/util/read.scala
- modules/core/src/test/scala/doobie/util/write.scala
- project/plugins.sbt
context: I'm trying to get doobie green in the Scala 2.13 community build, over at scala/community-build#1033
> bump Scala version to 2.13.1 (was 2.13.0)

- build.sbt
- modules/core/src/main/scala/doobie/hi/connection.scala
- modules/core/src/main/scala/doobie/syntax/applicativeerror.scala
- modules/core/src/main/scala/doobie/syntax/stream.scala
- modules/core/src/main/scala/doobie/util/catchsql.scala
- modules/core/src/main/scala/doobie/util/get.scala
- modules/core/src/main/scala/doobie/util/put.scala
- modules/core/src/main/scala/doobie/util/query.scala
- modules/core/src/main/scala/doobie/util/transactor.scala
- modules/core/src/test/scala/doobie/util/unapply.scala
- modules/example/src/main/scala/example/Coproduct.scala
- modules/example/src/main/scala/example/Noop.scala
- modules/free/src/main/scala/doobie/free/kleisliinterpreter.scala
- modules/postgres/src/main/scala/doobie/postgres/free/kleisliinterpreter.scala
- modules/postgres/src/main/scala/doobie/postgres/hi/connection.scala
- modules/postgres/src/main/scala/doobie/postgres/syntax/syntax.scala
- project/FreeGen2.scala
https://github.com/typelevel/kind-projector
>?, +?, and -? (deprecated syntax; same meaning as the above)
> Replace deprecated ? with *

- .gitignore
- build.sbt
- modules/docs/src/main/data/menu.yml
- modules/docs/src/main/tut/book.md
- modules/docs/src/main/tut/docs/01-Introduction.md
- modules/docs/src/main/tut/docs/02-Toolkit.md
- modules/docs/src/main/tut/docs/03-Connecting.md
- modules/docs/src/main/tut/docs/04-Selecting.md
- modules/docs/src/main/tut/docs/05-Parameterized.md
- modules/docs/src/main/tut/docs/06-Checking.md
- modules/docs/src/main/tut/docs/07-Updating.md
- modules/docs/src/main/tut/docs/08-Fragments.md
- modules/docs/src/main/tut/docs/09-Error-Handling.md
- modules/docs/src/main/tut/docs/10-Logging.md
- modules/docs/src/main/tut/docs/11-Arrays.md
- modules/docs/src/main/tut/docs/12-Custom-Mappings.md
- modules/docs/src/main/tut/docs/13-Unit-Testing.md
- modules/docs/src/main/tut/docs/14-Managing-Connections.md
- modules/docs/src/main/tut/docs/15-Extensions-PostgreSQL.md
- modules/docs/src/main/tut/docs/16-Extensions-H2.md
- modules/docs/src/main/tut/docs/17-Quill.md
- modules/docs/src/main/tut/docs/18-FAQ.md
- modules/docs/src/main/tut/index.md
- modules/docs/src/main/tut/infographic.md
- modules/docs/src/main/tut/migration.md
This PR basically creates a menu for the book sidebar, and fix main page horizontal menu positions.
If you feel like styles are misbehaving on some pages, check that you executing locally something like this (form the project root)
`jekyll serve -s ./modules/docs/target/site -b /doobie`
> Fix docsite

- modules/docs/src/main/mdoc/docs/15-Extensions-PostgreSQL.md
> Doc: postgres imports for java 8 time types

- modules/core/src/main/scala/doobie/util/fragments.scala
- modules/core/src/test/scala/doobie/util/fragments.scala
Useful for at least four people,
- me
- @dimitarg on [gitter](https://gitter.im/tpolecat/doobie?at=5cded51f75d9a575a6fa597d)
- @valenterry and @Esardes on #626
> Add fragments combinator for tuple

- modules/core/src/main/scala/doobie/util/read.scala
- modules/core/src/test/scala/doobie/util/read.scala
Fixes https://github.com/tpolecat/doobie/issues/1256
> `ap` on `Read` should combine in appropriate order

- build.sbt
- modules/docs/src/main/mdoc/docs/06-Checking.md
- modules/docs/src/main/mdoc/docs/13-Unit-Testing.md
- modules/munit/src/main/scala/doobie/munit/analysisspec.scala
- modules/munit/src/main/scala/doobie/munit/package.scala
- modules/munit/src/test/scala/doobie/munit/CheckerTests.scala
Adapted from https://github.com/tpolecat/doobie/pull/1233/files for CE3.
@Kazark @alejandrohdezma Let me know if you spot anything off :)
> Munit integration for 1.x branch

- modules/docs/src/main/mdoc/index.md
Thanks Doobie!
Also, fix the PR url for adding a new company
> Include the guardian in companies that use doobie

- modules/docs/src/main/mdoc/docs/12-Custom-Mappings.md
Hello,
I stumbled upon a broken link in the microsite and it was a quick fix. I hope I do things correctly, as I am not experienced in contributing.
Thanks for the great work!
> Fixed docs broken internal link for 12-Custom-Mappings

- modules/core/src/main/scala/doobie/util/get.scala
- modules/core/src/main/scala/doobie/util/write.scala
This PR addresses issue  #1597.
Let me know if I understood it wrong.
> Fixed name of the implicit val defining the function for the Get and Write types

- modules/docs/src/main/mdoc/docs/03-Connecting.md
> Add notes about different JDBC driver class name and URL

- modules/postgres/src/main/scala/doobie/postgres/pgisinstances.scala
- modules/postgres/src/test/scala/doobie/postgres/TypesSuite.scala
> Revert "Postgis: Add custom mapping for geography -> point postgres conversion"

- modules/docs/src/main/mdoc/index.md
We've been using Doobie since 2017!
> Adding my employer.

- modules/docs/src/main/mdoc/index.md
Added On Air Entertainment to the list of doobie adopters.
> Add On Air Entertainment to list of adopters.

- README.md
- modules/core/src/test/scala-2/doobie/util/ReadSuitePlatform.scala
- modules/core/src/test/scala-2/doobie/util/WriteSuitePlatform.scala
- modules/core/src/test/scala/doobie/issue/780.scala
- modules/core/src/test/scala/doobie/syntax/StringSuite.scala
- modules/core/src/test/scala/doobie/util/GetSuite.scala
- modules/core/src/test/scala/doobie/util/PutSuite.scala
- modules/core/src/test/scala/doobie/util/TransactorSuite.scala
- modules/core/src/test/scala/doobie/util/YoloSuite.scala
- modules/core/src/test/scala/doobie/util/arbitraries/SQLArbitraries.scala
- modules/core/src/test/scala/doobie/util/meta/MetaSuite.scala
- modules/free/src/main/scala/doobie/free/kleisliinterpreter.scala
- modules/h2/src/test/scala/doobie/h2/h2types.scala
- modules/munit/src/test/scala/doobie/munit/CheckerTests.scala
- modules/postgres/src/main/scala/doobie/postgres/free/kleisliinterpreter.scala
- modules/postgres/src/main/scala/doobie/postgres/syntax/FragmentSyntax.scala
- modules/postgres/src/test/scala/doobie/postgres/TextSuite.scala
- modules/postgres/src/test/scala/doobie/postgres/TypesSuite.scala
- project/FreeGen2.scala
The changes seemed that was already made seems to have disappeared..
> re-fix/suppress warnings & deprecations

- build.sbt
- modules/free/src/main/scala/doobie/WeakAsync.scala
- modules/free/src/main/scala/doobie/free/blob.scala
- modules/free/src/main/scala/doobie/free/callablestatement.scala
- modules/free/src/main/scala/doobie/free/clob.scala
- modules/free/src/main/scala/doobie/free/connection.scala
- modules/free/src/main/scala/doobie/free/databasemetadata.scala
- modules/free/src/main/scala/doobie/free/driver.scala
- modules/free/src/main/scala/doobie/free/kleisliinterpreter.scala
- modules/free/src/main/scala/doobie/free/nclob.scala
- modules/free/src/main/scala/doobie/free/preparedstatement.scala
- modules/free/src/main/scala/doobie/free/ref.scala
- modules/free/src/main/scala/doobie/free/resultset.scala
- modules/free/src/main/scala/doobie/free/sqldata.scala
- modules/free/src/main/scala/doobie/free/sqlinput.scala
- modules/free/src/main/scala/doobie/free/sqloutput.scala
- modules/free/src/main/scala/doobie/free/statement.scala
- modules/free/src/test/scala/doobie/WeakAsyncSuite.scala
- modules/postgres/src/main/scala/doobie/postgres/free/copyin.scala
- modules/postgres/src/main/scala/doobie/postgres/free/copymanager.scala
- modules/postgres/src/main/scala/doobie/postgres/free/copyout.scala
- modules/postgres/src/main/scala/doobie/postgres/free/kleisliinterpreter.scala
- modules/postgres/src/main/scala/doobie/postgres/free/largeobject.scala
- modules/postgres/src/main/scala/doobie/postgres/free/largeobjectmanager.scala
- modules/postgres/src/main/scala/doobie/postgres/free/pgconnection.scala
- project/FreeGen2.scala
Closes https://github.com/tpolecat/doobie/issues/1852.
> Update to Cats Effect v3.5.0

- modules/core/src/main/scala/doobie/util/fragments.scala
- modules/core/src/test/scala/doobie/util/FragmentsSuite.scala
> Add orFallbackFalse, andFallbackTrue

- modules/docs/src/main/mdoc/docs/14-Managing-Connections.md
- modules/hikari/src/main/scala/doobie/hikari/HikariTransactor.scala
> HikariTransactor: Default logHandler to None

- build.sbt
> Revert Slf4j 2.x

- modules/docs/src/main/mdoc/index.md
We've been using Doobie for years (first version we used that appears in git log is `0.3.0-M1` ;-)). It's a fantastic library with great documentation. We couldn't be more thankful to you!
> Add Intent HQ to list of adopters

- modules/core/src/main/scala/doobie/util/package.scala
also remove unused method void
fixed #1923
> Expose "unlabelled" as a constant

- modules/docs/src/main/mdoc/index.md
Exceptionally happy Doobie adopters since 0.13.4 :)
> Input Objects GmbH adopter

- CONTRIBUTING.md
- modules/core/src/main/scala/doobie/hi/preparedstatement.scala
- modules/core/src/main/scala/doobie/util/update.scala
- modules/docs/src/main/mdoc/docs/02-Toolkit.md
> [Doc] Explain the F and C in doobie.FC/HC

- modules/docs/src/main/mdoc/docs/18-Related-Projects.md
- modules/docs/src/main/mdoc/docs/index.md
Added a list of related projects that people otherwise might not find.
> docs: related projects

- modules/core/src/main/scala/doobie/util/fragments.scala
This fixes some outdated comments.
> Fix outdated comments

- build.sbt
munit to 1.1.0
cats to 2.13.0
Switch munit-cats-effect-3 to munit-cats-effect
> Upgrade deps (minor)

- modules/mysql/src/test/scala/doobie/mysql/TypesSuite.scala
- modules/postgres/src/test/scala/doobie/postgres/TextSuite.scala
- modules/postgres/src/test/scala/doobie/postgres/TypesSuite.scala
> Reduce MinSuccessfulTests to reduce some test suites' execution time

- modules/core/src/main/scala-3/doobie/util/shapeless/OrElse.scala
> Fix NPE due to Scala 3 by-name implicit bug

- modules/core/src/main/scala/doobie/util/fragment.scala
- modules/core/src/main/scala/doobie/util/query.scala
- modules/core/src/main/scala/doobie/util/transactor.scala
- modules/refined/src/main/scala/doobie/refined/Instances.scala
prepare latest Scala 3.x
- https://github.com/scala/scala3/pull/22441
> add `using` clause

- modules/core/src/main/scala/doobie/util/get.scala
- modules/core/src/main/scala/doobie/util/put.scala
- modules/core/src/main/scala/doobie/util/write.scala
> Rid of anonymous `Get`s and `Put`s
