typelevel/doobie

doc/src/main/tut/02-Toolkit.md
Based on [IO Monad considered harmful](http://blog.jle.im/entry/io-monad-considered-harmful) I find it more appropriate to talk about data types and only refer to the the monad in the context of the monadic properties of these data types (eg. when `flatMap`, for-comprehension, etc. come into play).
=> Use 'data type' instead of 'monad'.

contrib/h2/src/test/scala/doobie/contrib/h2/h2types.scala, contrib/postgresql/src/test/scala/doobie/contrib/postgresql/pgtypes.scala, core/src/main/scala/doobie/hi/preparedstatement.scala, core/src/main/scala/doobie/imports.scala, core/src/main/scala/doobie/util/update.scala, doc/src/main/tut/07-Updating.md
This adds high-level support for batch updates.
- Re-exports `FPS.addBatch` and `FPS.executeBatch` from `HPS`.
- Adds `HPS.addBatches` and `HPS.addBatchesAndExecute`.
- Adds `Update.updateMany`.
- Adds initial tut doc.
- Adds `Update`, `Update0`, `Query`, and `Query0` to `imports`.
fixes #79
=> batch updates

.travis.yml, contrib/postgresql/README.md, contrib/postgresql/build.sbt, contrib/postgresql/src/main/scala/doobie/contrib/postgresql/pgtypes.scala, contrib/postgresql/src/test/scala/doobie/contrib/postgresql/pgtypes.scala, doc/src/main/tut/01-Introduction.md
This adds support for the main PostGIS types:
- `PGgeometry`
- `PGbox2d`
- `PGbox3d`
As well as the following abstract and fine-grained types carried by `PGgeometry`:
- `Geometry`
- `ComposedGeom`
- `GeometryCollection`
- `MultiLineString`
- `MultiPolygon`
- `PointComposedGeom`
- `LineString`
- `MultiPoint`
- `Polygon`
- `Point`
fixes #82 
cc @aloiscochard @icassina
=> PostGIS support

core/src/main/scala/doobie/syntax/connectionio.scala, core/src/main/scala/doobie/syntax/process.scala, core/src/main/scala/doobie/util/transactor.scala
This PR restructures `Transactor` as a pair of natural transformations, which is a nicer representation with better compositional properties. It also makes the ancillary operations (preparation, cleanup, etc.) overridable by implementations.
=> clean up transactor a bit

contrib/hikari/src/main/scala/doobie/contrib/hikari/HikariTransactor.scala, example/src/main/scala/example/HikariExample.scala
As reported by @ppurang in the gitter channel, the Hikari transactor doesn't really work unless you load the driver class by hand. So this PR adds it as a ctor parameter and restores the example. This is a **breaking change** and will need doc. Fixes #127 pending doc.
=> add driver class to hikari ctor

contrib/h2/src/test/scala/doobie/contrib/h2/h2types.scala, core/src/main/scala/doobie/hi/preparedstatement.scala, core/src/main/scala/doobie/util/meta.scala
This fixes #123 by adding jdbc `BOOLEAN` as an acceptable primary mapping for Scala `Boolean` values and adds a test for H2, where the bug was reported. This mapping doesn't appear in the jdbc spec but that's certainly an oversight.
It also fixes a bug discovered along the way that made analysis fail for zero-param queries constructed with the `sql` interpolator ... the scalaz `|->` operator can go forwards or backwards so `1 |-> 0` is actually `List(1,0)` instead of `Nil`, which made `HNil` appear to have two elements instead of zero. Anyway, fixed.
=> Add Jdbc BOOLEAN for Meta[Boolean] mapping

core/src/main/scala/doobie/util/composite.scala
Sadly this was generating stack overflows with the following test
```scala
object compositespec extends Specification {
case class Woozle(a: (String, Int), b: Int :: String :: HNil, c: Boolean)
"Composite" should { 
"exist for some fancy types" in {
Composite[(Woozle, String)]
true
}
}
```
Reverts tpolecat/doobie#126
=> Revert "Composite instance for Generic"

core/src/test/scala/doobie/util/composite.scala
Add some sanity checks for derivations, since they were failing in our attempts to be fancier with shapeless. Also add a test to verify that prioritization isn't broken.
=> initial composite spec

build.sbt, contrib/postgresql/src/main/scala/doobie/contrib/postgresql/syntax.scala, contrib/postgresql/src/test/scala/doobie/contrib/postgresql/unapply.scala, core/build.sbt, core/src/main/scala/doobie/imports.scala, core/src/test/scala/doobie/util/unapply.scala
This adds an unapplied implicit constructor for `Monad[Free[Coyoneda[F, ?], ?]]` and an `Unapply` instance matching this shape. This prevents you from losing the `Monad` instance and associated syntax for things like `ConnectionIO` after the alias has been expanded.
Also adds [Kind Projector](https://github.com/non/kind-projector).
This fixes #124 and fixes #57.
Many thanks to Stephen Compall for helping me figure this out.
=> Unapply for FreeCoyo

core/src/main/scala/doobie/enum/parametermode.scala
**Disclaimer: I have no idea what I'm doing**
Currently on 0.2.1, running Analysis on a database that doesn't return proper metadata for prepared statements (SQL Server 2008r2 via jTDS 1.3.1 for anyone interested) throws an `InvalidOrdinal: 0`
```
[info] Query0[(Option[Int], Option[String], Option[Timestamp], Option[Timestamp])] defined at Alpha.scala:14
[info]   
[info]   SELECT ProjectId, Cycle, DateStart, DateFinish FROM tblCycle
[info]   WHERE DateStart > ? AND DateFinish < ?
[info]   
[error]   x SQL Compiles and Typechecks
[error]    x doobie.enum.parametermode$ParameterMode: invalid ordinal: 0 (specs2.scala:61)
```
This is because the parametermode enum doesn't have a representation for `parameterModeUnknown` from `java.sql.ParameterMetaData`. This PR adds one.
```
[info] …
```
=> Add ModeUnknown to ParameterMode enum

contrib/postgresql/src/test/scala/doobie/contrib/postgresql/pgnotify.scala
My theory is that the builds end up running in parallel and occasionally clobber each other's notifications. I don't have a better idea. It only fails on travis, and only occasionally.
=> attempt to fix sporadic pgnotify test failure

core/src/main/scala/doobie/util/transactor.scala, doc/src/main/tut/12-Managing-Connections.md
This adds some overloads to support variants of `DriverManager.getConnection`. Not a general solution but it resolves #170.
=> More DriverManagerTransactor ctors

core/src/main/scala/doobie/util/analysis.scala, doc/src/main/tut/06-Checking.md
This PR removes the check for needlessly lifted types (`Option` when no `NULL` values are expected) because JDBC's `NoNulls` metadata is useless ("might not be nullable"). 
Resolves #164
=> ignore useless NoNulls in analysis

core/src/main/scala/doobie/util/composite.scala, core/src/test/scala/doobie/util/composite.scala, doc/src/main/tut/04-Selecting.md, doc/src/main/tut/10-Custom-Mappings.md
This adds support for `Composite` of shapeless records, and resolves #144.
=> Shapeless records

core/src/main/scala/doobie/enum/jdbctype.scala
This adds two new `JdbcType` constants that are outside the JDBC specification and prevent query analysis from working. Fixes #218
=> add ms-sql jdbc types

core/src/main/scala/doobie/imports.scala, core/src/main/scala/doobie/syntax/string.scala, core/src/test/scala/doobie/syntax/string.scala, doc/src/main/tut/05-Parameterized.md, doc/src/main/tut/10-Custom-Mappings.md
This adds a `Param` typeclass that's used only by the `sql` interpolator. This ensures that we can't use arbitrary `Composite` instances as parameters and thus resolves #202. It also provides a way to do `IN` clauses and thus resolves #80.
=> param typeclass, in-clause support

contrib/specs2/src/main/scala/doobie/contrib/specs2/specs2.scala, core/src/main/scala/doobie/util/query.scala, core/src/main/scala/doobie/util/yolo.scala, doc/src/main/tut/06-Checking.md
Forked from #230 ... added `checkOutput` to `Yolo`.
(Also rebased, not that it matters.)
In a lame way this
- resolves #231
- resolves #228 
- resolves #222
=> metadata analysis of query output

build.sbt, core/src/main/scala/doobie/syntax/string.scala, core/src/main/scala/doobie/util/composite.scala, core/src/test/scala/doobie/util/composite.scala
This PR updates kind-projector and replaces `ProductTypeClass` with a more straightforward use of `Generic`. It also adds some tests that take a long time to compile ... `compositespec` takes about 40s on my machine, but it does terminate. This resolves #217
=> kp 0.7.1, replace ProductTypeclass

core/src/main/scala/doobie/imports.scala
I had copied `freeMonadC` and `unapplyMMFA` into my own project, but they wouldn't work for me until I added the result type to `freeMonadC`.  Thought you might want it here too, for good measure.
=> add result type to imports.freeMonadC

core/src/main/scala/doobie/hi/resultset.scala, core/src/main/scala/doobie/util/query.scala, core/src/test/scala/doobie/util/query.scala, doc/src/main/tut/04-Selecting.md
What do you think about this, to convert the following sort of construction (and its accompanying warning):
```scala
implicit class toNelUnsafe[F[_] : Functor, A](fa: F[List[A]]) {
def toNelUnsafe: F[NonEmptyList[A]] = fa map {
case a :: as => NonEmptyList.nel(a, as) // not total
}
}
def getItems(orderId: OrderId): ConnectionIO[NonEmptyList[ItemId]] =
sql"""
SELECT item_id FROM order_contents WHERE order_id = $orderId
""".query[ItemId].list.toNelUnsafe
```
into 
```scala
def getItems(orderId: OrderId): ConnectionIO[NonEmptyList[ItemId]] =
sql"""
SELECT item_id FROM order_contents WHERE order_id = $orderId
""".query[ItemId].nel // safe!
```
P.S. Some whitespace changes got caught up in the first commit too, despite having carefully reverted them once; I converted some legacy tabs to spaces …
=> add NonEmptyList `.nel` support to RS, Query, Query0, docs

contrib/hikari/src/main/scala/doobie/contrib/hikari/HikariTransactor.scala
This PR allows reusing `HikariDataSource` instances potentially initialized elsewhere (ex. Play DB facilities) to construct Doobie's `HikariTransactor`.
@tpolecat Thanks for your consideration!
=> Allow construction of `HikariTransactor` instances from an existing `HikariTransactorDatasource`

build.sbt, yax/bench/src/main/scala/doobie/bench/bench.scala, yax/core/src/main/scala/doobie/hi/connection.scala, yax/core/src/main/scala/doobie/hi/package.scala, yax/core/src/main/scala/doobie/hi/preparedstatement.scala, yax/core/src/main/scala/doobie/hi/resultset.scala, yax/core/src/main/scala/doobie/util/process.scala, yax/core/src/main/scala/doobie/util/query.scala, yax/core/src/main/scala/doobie/util/update.scala, yax/core/src/test/scala/doobie/util/process.scala, yax/docs/src/main/tut/04-Selecting.md, yax/docs/src/main/tut/05-Parameterized.md
This changes the streams constructed by `Query/0` and `Update/0` to emit rows in chunks rather than one by one. Right now the chunk size is fixed at 512.
Before we see a slowdown of ~14x for fs2 and ~5x for scalaz-stream for resultsets on the order of 10^5 rows:
After chunking we see fs2 performance closing in on raw JDBC ~1.3x or better for large resultsets, and scalaz-stream with a slowdown of ~2x. Much better.
There are API changes to `HC`, `HPS`, and `HRS` modules: all methods that construct streams now have a `chunkSize: Int` parameter. It's not terribly common to call these so I doubt it will affect very many users.
So, more to do:
/cc @jedesah
=> WIP: chunked streaming

.travis.yml, project/travis-before-build.sh, project/travis-build.sh
- Use build matrix with different commands according to scala versions
- Use SBT/Ivy cache
The cache sometimes causes weird build failure which needs a manual flush, but it's unusual case and generally works good.
=> Boost Travis build using some tricks from https://monix.io

README.md, build.sbt, project/build.properties, yax/core/src/main/scala/doobie/util/compat.scala, yax/core/src/main/scala/doobie/util/transactor.scala
The only breaking change was removal of `Stream#onComplete`. To replace it with `onFinalize` [as recommended](https://github.com/functional-streams-for-scala/fs2/blob/v0.9.0-RC1/docs/guide.md#-appendix-a2-how-interruption-of-streams-works), I had to add one more implicit conversion from `cats.Monad` to `fs2.util.Monad` to compat module.
=> Update to fs2 0.9.0-RC1

README.md, build.sbt
I've noticed README shows old version... and I've also bumped versions... that should be fine I guess
=> Readme fix, minor version bump

build.sbt
... just being nice to people who are getting fs2 only via transitive dependency ...
=> fs2 0.9.0 -> 0.9.1

build.sbt, yax/core/src/main/scala/doobie/enum/jdbctype.scala, yax/postgres/src/main/scala/doobie/postgres/free/pgconnection.scala
Since doobie 0.3 depends on jdk8+ , can't we use hikariCP for java8 for 0.3.1 ?
=> bump h2, postgresql and hikariCP versions

build.sbt, project/travis-build.sh, yax/core/src/main/scala/doobie/syntax/catchable.scala, yax/core/src/main/scala/doobie/util/yolo.scala, yax/core/src/test/scala/doobie/syntax/catchable.scala, yax/docs/src/main/tut/01-Introduction.md, yax/docs/src/main/tut/03-Connecting.md, yax/docs/src/main/tut/05-Parameterized.md, yax/docs/src/main/tut/07-Updating.md, yax/docs/src/main/tut/08-Error-Handling.md, yax/docs/src/main/tut/09-Arrays.md, yax/docs/src/main/tut/10-Custom-Mappings.md, yax/docs/src/main/tut/11-Unit-Testing.md, yax/docs/src/main/tut/13-Extensions-PostgreSQL.md, yax/docs/src/main/tut/14-Extensions-H2.md
It seems that the first `exec` replaces the shell and swallows the following ones. [1]  This PR just merges all sbt commands into a single run.
[1] http://stackoverflow.com/a/7194536
=> Run tut in Travis builds (fix #362)

yax/core/src/main/scala/doobie/util/meta.scala, yax/core/src/test/scala/doobie/util/meta.scala
`Meta` instances are registered on construction as a side-effect. This is used by query checking to provide hints about known mappings if the asserted ones don't work.
In 0.3.0 there is a `scalaz.Order[Meta[_]]` and the instances live in an `ISet` but this doesn't work in Cats, so I temporarily switched it to `Set` to get things compiling but I never switched it back to a set that uses reasonable equality, which resulted in #394 … inductively derived instances were getting re-registered.
This fixes that by defining both `scalaz.Order` and `cats.Order`, and from there deriving `scala.Ordering` and using a `TreeSet` as storage.
fixes #394
=> Fix Meta registration

yax/core/src/main/scala/doobie/util/invariant.scala, yax/core/src/test/scala/doobie/util/invariant.scala
I'm happy to do this differently if you like. I considered adding the disclaimer to the `MappingViolation` constructor.
It seemed likely that there'd be a need to add the disclaimer to a message in `yax/core/src/main/scala/doobie/util/analysis.scala`. However I couldn't find any messages which included the index, so I didn't make a change there. It might be worth double-checking my (non-)work in that file.
=> Add disclaimer about 1-based JDBC indexing to MappingViolation instances

build.sbt, yax/docs/src/main/tut/13-Unit-Testing.md, yax/example/src/test/scala/doobie/AnalysisTestScalaTest.scala, yax/example/src/test/scala/doobie/AnalysisTestSpecs2.scala, yax/scalatest/src/main/scala/doobie/scalatest/QueryChecker.scala, yax/specs2/src/main/scala/doobie/specs2/specs2.scala
Various fixes for ScalaTest. Issue #406 requested that output be shown on success but there's not a way I can see to output a success message … I can print to the console but it's disconnected from the test summary so you don't know what test it's associated with.
There were some formatting issues I fixed, and it was running the analysis twice which wasn't ideal. The mixin was also over-constrained with a `FunSuite` self-type, which has been widened to `Assertions` so it can work with any ScalaTest style.
Todo:
=> ScalaTest output formatting, assertions.

README.md
In the old link it was possible for some browser configurations to spawn a new open request each time one opened, infinitely looping until browser crash.
=> Replaces a link with potentially chain-opening behaviour

yax/core/src/main/scala/doobie/util/lens.scala, yax/core/src/main/scala/doobie/util/transactor.scala, yax/core/src/test/scala/doobie/util/lens.scala
This adds some more functionality to the wee `Lens` implementation to make it more useful, and adds a void `Strategy` that does nothing. See #460
=> transactor helpers

CHANGELOG.md, yax/core/src/main/scala/doobie/util/query.scala
`Query` was missing some convenient shortcuts present in `Query0`
=> Add missing methods to Query

CHANGELOG.md, README.md, build.sbt, project/build.properties
per https://github.com/typelevel/scala/issues/135
=> sbt 0.13.13; crossVersion.full -> .patch

project/FreeGen2.scala, yax/core/src/main/scala/doobie/free/blob.scala, yax/core/src/main/scala/doobie/free/callablestatement.scala, yax/core/src/main/scala/doobie/free/clob.scala, yax/core/src/main/scala/doobie/free/connection.scala, yax/core/src/main/scala/doobie/free/databasemetadata.scala, yax/core/src/main/scala/doobie/free/driver.scala, yax/core/src/main/scala/doobie/free/nclob.scala, yax/core/src/main/scala/doobie/free/preparedstatement.scala, yax/core/src/main/scala/doobie/free/ref.scala, yax/core/src/main/scala/doobie/free/resultset.scala, yax/core/src/main/scala/doobie/free/sqldata.scala, yax/core/src/main/scala/doobie/free/sqlinput.scala, yax/core/src/main/scala/doobie/free/sqloutput.scala, yax/core/src/main/scala/doobie/free/statement.scala
This adds a `fail` constructor to each language. Resolves #479 
Relying on existing tests for error handling combinators.
=> add fail ctor

build.sbt
This upgrades refined to 0.7.0 in the hope that it will fix the sporadic build failure described in https://github.com/fthomas/refined/issues/260.
=> refined 0.7.0

yax/refined/src/test/scala/doobie/refined/refinedtypes.scala
Using refined's macro in doobies tests leads to nondeterministic
compiler crashes (https://github.com/fthomas/refined/issues/260).
Fortunately these macros are not essential for testing doobie-refined,
so I removed its usage from the tests.
=> Do not use refined's macros in tests

CHANGELOG.md, yax/core/src/main/scala/doobie/util/composite.scala, yax/core/src/test/scala/doobie/util/composite.scala
`Composite[Unit]` has the same meaning as `Composite[HNil]`.
It allows fields that are ignored by database mapping. Such fields are useful for parametric types.
For example:
```scala
case class Topic[A](name: String, posts: A)
type TopicWithoutPosts = Topic[Unit]
// note there is only one column in select statement
sql"select name from topic".query[TopicWithoutPosts]
```
=> Composite instance for Unit

CHANGELOG.md, build.sbt, yax/docs/src/main/tut/13-Unit-Testing.md, yax/example/src/test/scala/doobie/AnalysisTestScalaTest.scala, yax/scalatest/src/main/scala/doobie/scalatest/Checker.scala, yax/scalatest/src/main/scala/doobie/scalatest/imports.scala, yax/scalatest/src/test/scala/doobie/scalatest/CheckerTests.scala
This lets the scalacheck trait work with an arbitrary effect type.
resolves #448
=> generic effect type for scalacheck

CHANGELOG.md, yax/core/src/main/scala/doobie/util/query.scala
As discussed in gitter, alias methods for `.stream` and `streamWithChunkSize`
=> Stream Alias for Query

yax/example/src/main/scala/example/GenericStream.scala
Example of reading into a stream of untyped maps. Once we get on cats we can try to bring some reusability to `liftProcess`.
=> generic-demo

CHANGELOG.md, yax/h2/src/main/scala/doobie/h2/h2types.scala, yax/h2/src/test/scala/doobie/h2/h2types.scala
Fixes a portion of #552. I haven't been able to figure out what's up with merge statements reporting VARCHAR for every type.. I was able to kind of fix it by using the composite to set the params before running the analysis, but things still acted funky in situations involving NULL.
=> Fix analysis when using h2 + UUIDs

yax/core/src/main/scala/doobie/imports.scala, yax/core/src/main/scala/doobie/syntax/connectionio.scala, yax/core/src/main/scala/doobie/syntax/process.scala, yax/core/src/main/scala/doobie/util/transactor.scala, yax/core/src/main/scala/doobie/util/yolo.scala, yax/core/src/test/scala/doobie/issue/262.scala, yax/example/src/main/scala/example/StreamingCopy.scala, yax/h2/src/main/scala/doobie/h2/H2Transactor.scala, yax/hikari/src/main/scala/doobie/hikari/HikariTransactor.scala, yax/scalatest/src/main/scala/doobie/scalatest/Checker.scala, yax/specs2/src/main/scala/doobie/specs2/specs2.scala
Type parameter `A` is removed from `Transactor` type signature. `Transactor` constructor now return `Aux` type so that you can retain `A` or throw it away if you don't need it.
=> Hide extra type parameter in `Transactor`

yax/hikari/src/main/scala/doobie/hikari/HikariTransactor.scala
This bug exists only in `series/0.4.x`.
https://github.com/tpolecat/doobie/blob/series/0.5.x/modules/hikari/src/main/scala/doobie/hikari/HikariTransactor.scala#L24-L25
=> fix HikariTransactor.apply

CHANGELOG.md, PUBLISHING.md, build.sbt, version.sbt
Ok this simplifies the release. Not as much as I'd like but it's a lot better. The big revelation is that `releaseCrossBuild` and `releaseProcess` need to be defined *only* in the top-level project, and `releaseProcess` should be `Nil` everywhere else just to prevent confusion.  And `publishMicrosite` can't be a `ReleaseStep` because computer says no (see https://github.com/47deg/sbt-microsites/issues/210).
I tried setting up automatic releases but it's too fucking complicated. I need to do it from scratch on a dummy project first, then document the hell out of it.
=> update release process

yax/docs/src/main/tut/01-Introduction.md
The already existing link does not work (probably because master branch has been deleted). The one I used works.
I spent 5 minutes looking for that, hope this PR will save this time for others :)
=> link to world.sql file fixed in docs

modules/postgres/src/main/scala/doobie/postgres/Instances.scala, modules/postgres/src/test/scala/doobie/postgres/pgtypes.scala
This exposes the default `PGInterval` mapping provided by the driver. No mapping to a JDK type is attempted, see the discussion in #315.
=> PGInterval

modules/core/src/main/scala/doobie/util/param.scala
This makes `Param` constructor public again.
=> Make Param constructor public

.travis.yml, build.sbt, modules/docs/src/main/tut/docs/12-Custom-Mappings.md
_This PR is for cats-1.0.0 branch #650_
We've been still caching `~/.sbt/0.13` after migrating to sbt 1.0. I'm not sure it's the most significant cause of increaset build time, but it must be helpful.
Bumped to circe 0.9 as well, including example docs.
=> [cats-1.0.0] Update Travis cache setup, bump to circe 0.9

.travis.yml, build.sbt, modules/core/src/main/scala/doobie/syntax/stream.scala, modules/core/src/test/scala/doobie/util/process.scala, modules/docs/src/main/tut/docs/04-Selecting.md, modules/example/src/main/scala/example/StreamingCopy.scala, modules/postgres/src/test/scala/doobie/postgres/manyrows.scala
_This PR is for cats-1.0.0 branch #650_
Updated to FS2 0.10.0-M11 and Scala 2.11.12.
In FS2, `Stream#run*` are deprecated in favor of `Stream#compile{.drain, .toVector, .toList, ...}`. Should we do something similar about `Update#run`? At this point, `.run` looks a bit misleading to me.
https://github.com/functional-streams-for-scala/fs2/blob/v0.10.0-M11/docs/migration-guide-0.10.md#compiling--interpreting-streams
=> Update fs2 to 0.10.0-M11

modules/core/src/main/scala/doobie/syntax/stream.scala, modules/core/src/main/scala/doobie/util/transactor.scala
fs2 removed the `Effect` constraint on `transform` so we can weaken `Stream.transact` to `Monad`
=> weaken Effect to Monad

modules/scalatest/src/main/scala/doobie/scalatest/AnalysisMatchers.scala, modules/specs2/src/main/scala/doobie/specs2/analysisspec.scala, project/build.properties
This uses `IO.ioEffect` to find the `implicit val M: Effect[IO]` in `IOChecker` and `IOAnalysisMatchers`. Without this, I had some runtime issues with uninitialized fields when attempting to find the implicit `Effect`.
(also update sbt to 1.1.0 final)
=> Use `IO.ioEffect` to find `Effect[IO]` in test modules

modules/core/src/main/scala/doobie/util/stream.scala, modules/core/src/main/scala/doobie/util/transactor.scala
I've also removed `VoidStreamOps` syntax in `Strategy`. It's redundant and makes code less straightforward IMHO. I'll undelete it, if you think it's useful.
=> simplify `repeatEvalChunks`

modules/bench/src/main/scala/doobie/bench/select.scala, modules/core/src/main/scala/doobie/syntax/stream.scala, modules/core/src/main/scala/doobie/util/query.scala, modules/core/src/main/scala/doobie/util/yolo.scala, modules/core/src/test/scala/doobie/util/strategy.scala, modules/docs/src/main/tut/docs/01-Introduction.md, modules/docs/src/main/tut/docs/02-Toolkit.md, modules/docs/src/main/tut/docs/03-Connecting.md, modules/docs/src/main/tut/docs/04-Selecting.md, modules/docs/src/main/tut/docs/05-Parameterized.md, modules/docs/src/main/tut/docs/06-Checking.md, modules/docs/src/main/tut/docs/07-Updating.md, modules/docs/src/main/tut/docs/08-Fragments.md, modules/docs/src/main/tut/docs/09-Error-Handling.md, modules/docs/src/main/tut/docs/10-Logging.md, modules/docs/src/main/tut/docs/11-Arrays.md, modules/docs/src/main/tut/docs/12-Custom-Mappings.md, modules/docs/src/main/tut/docs/13-Unit-Testing.md, modules/docs/src/main/tut/docs/14-Managing-Connections.md, modules/docs/src/main/tut/docs/15-Extensions-PostgreSQL.md, modules/docs/src/main/tut/docs/16-Extensions-H2.md, modules/docs/src/main/tut/docs/17-FAQ.md, modules/docs/src/main/tut/migration.md, modules/example/src/main/scala/example/FirstExample.scala, modules/example/src/main/scala/example/GenericStream.scala, modules/example/src/main/scala/example/HiUsage.scala, modules/example/src/main/scala/example/PostgresNotify.scala
This is a lot of little changes but I think it covers all the important stuff. No more mentions of `Catchable`, `Suspend`, `Process`, etc. It also gets rid of the `Stream` syntax other than `.transact` ... we don't need to be in the business of providing general-purpose syntax for fs2.
=> update doc for 0.5.0

modules/bench/src/main/scala/doobie/bench/select.scala, modules/core/src/main/scala/doobie/hi/connection.scala, modules/core/src/main/scala/doobie/hi/preparedstatement.scala, modules/core/src/main/scala/doobie/hi/resultset.scala, modules/core/src/main/scala/doobie/util/query.scala, modules/core/src/test/scala/doobie/util/query.scala, modules/docs/src/main/tut/docs/04-Selecting.md, modules/docs/src/main/tut/docs/05-Parameterized.md, modules/docs/src/main/tut/docs/10-Logging.md, modules/docs/src/main/tut/docs/17-FAQ.md, modules/docs/src/main/tut/migration.md, modules/example/src/main/scala/example/Coproduct.scala, modules/example/src/main/scala/example/FirstExample.scala, modules/example/src/main/scala/example/GenericStream.scala, modules/example/src/main/scala/example/HiUsage.scala, modules/example/src/main/scala/example/PostgresPoint.scala, modules/postgres/src/test/scala/doobie/postgres/manyrows.scala
This deprecates `process` in the highest-level API and just renames it in the lower APIs. Also deprecates `.list` and `.vector` to encourage users to use the more general `.to[F]`.
=> process → stream

modules/example/src/main/scala/example/FirstExample.scala
If you're like me, you probably messed something up with your
dependencies or the database parameters while trying to run the first
example, but confusingly it gives no output.
sbt:doobie> example/runMain example.FirstExample
[info] Running example.FirstExample
[success] Total time: 9 s, completed Mar 16, 2018 12:16:28 AM
I changed the last statement to
IO(println(str)).
Instead of,
IO(str)
An error produces the following output:
sbt:doobie> example/runMain example.FirstExample
[info] Running example.FirstExample
Left(No suitable driver found)
[success] Total time: 18 s, completed Mar 16, 2018 12:17:32 AM
And on success,
sbt:doobie> example/runMain example.FirstExample
[info] Running example.FirstExample 
Inserted 3 suppliers and 5 coffees.
Coffee(Colombian,101,7.99,0,0)
... …
=> Print either result in first example

.travis.yml
I'm kind of assuming it won't build now because we accidentally broke bincompat because it wasn't being checked. Let's see...
=> fix MAIN_SCALA_VERSION in travis build

modules/example/src/main/scala/example/CallableStatementExample.scala, world.sql
This PR add an example of a callable statement (stored procedure) using the free api.
The example was taken from issue #273.
=> Add a callable statement example.

modules/core/src/main/scala/doobie/syntax/foldable.scala, modules/core/src/main/scala/doobie/util/analysis.scala, modules/core/src/main/scala/doobie/util/foldable.scala, modules/core/src/main/scala/doobie/util/package.scala, modules/core/src/main/scala/doobie/util/query.scala, modules/core/src/main/scala/doobie/util/update.scala, modules/core/src/main/scala/doobie/util/yolo.scala
This removes some code that has become unnecessary.
- Removed `Foldable.foldSmash` as it's now provided by Cats.
- Removed `Foldable.element` as it's now provide by Cats as `contains_`.
- Removed `NonEmptyList.list` in favor of `toList`.
- Simplified `Query` and `Update1:
- Removed explicit `MonadError` missing syntax workaround that's no longer needed.
- Removed built-in coyoneda stuff which is no longer necessary due to `Read` and `Write` being independent now.
- Deprecated `Query0.sink` (should have been done earlier, oops) and removed usage in `Yolo`.
- Removed methods deprecated in 0.5.x
=> misc. simplifications

modules/docs/src/main/tut/docs/17-FAQ.md
The link in chapter 17-FAQ towards "Custom mapping" chapter should be `12-...` in place of `10-...`
=> Issue #743: Correct link in FAQ to custom-mapping

modules/postgres/src/main/scala/doobie/postgres/Text.scala
This fixes the "diverging implicit" error when using `Text` with nested case classes.
=> fix Text for nested case classes

modules/core/src/main/scala/doobie/util/param.scala, modules/core/src/test/scala/doobie/issue/780.scala, modules/core/src/test/scala/doobie/util/param.scala
As far as I can tell, this solves the issue without introducing any new ambiguous implicit errors. I don't know how scala's implicit resolution works though. This could've broken things.
=> Resolve diverging implicit expansion problem (#780)

modules/docs/src/main/tut/migration.md
With a mention about the partial equivalents in Get/Put.
=> Correct Meta[A].`tmap` to `timap` in 0.6 migration guide

modules/core/src/main/scala/doobie/util/param.scala, modules/core/src/main/scala/doobie/util/put.scala, modules/core/src/test/scala/doobie/issue/780.scala
This should resolve #780 in the 6.x series.
Moving priorities around didn't work, so I had to resort to using `shapeless.Lazy`.  It doesn't seem to be causing any new problems.
Also fixed a couple of typos in `put.scala` while I was poking around.
cc: @mcanlas
=> Port fix from #782 in to 6.x

build.sbt, modules/core/src/main/scala/doobie/util/param.scala, modules/core/src/test/scala/doobie/issue/780.scala
This upgrades cats on series 0.5.x to the latest cats version which has a corresponding stable cats-effect version.
Additionally when making this, I discovered that my solution to #780 only worked _sometimes_.  In partial compiles, it compiled fine.  In full-rebuilds, it would not.  I've switched it to use the solution found in #797, which works consistently.
=> Upgrade cats version

modules/docs/src/main/tut/docs/03-Connecting.md, modules/docs/src/main/tut/docs/04-Selecting.md, modules/docs/src/main/tut/docs/05-Parameterized.md, modules/docs/src/main/tut/docs/06-Checking.md, modules/docs/src/main/tut/docs/07-Updating.md, modules/docs/src/main/tut/docs/08-Fragments.md, modules/docs/src/main/tut/docs/09-Error-Handling.md, modules/docs/src/main/tut/docs/10-Logging.md, modules/docs/src/main/tut/docs/11-Arrays.md, modules/docs/src/main/tut/docs/13-Unit-Testing.md, modules/docs/src/main/tut/docs/14-Managing-Connections.md, modules/docs/src/main/tut/docs/15-Extensions-PostgreSQL.md, modules/docs/src/main/tut/docs/17-FAQ.md
=> Fix documentation typo

build.sbt
This dependency was added in https://github.com/tpolecat/doobie/pull/481
which updated refined to 0.7.0. This version required the scala-compiler
dependency as mentioned in the release notes here:
https://github.com/fthomas/refined/blob/master/notes/0.7.0.markdown
refined 0.8.0 dropped this requirement again
(https://github.com/fthomas/refined/blob/master/notes/0.8.0.markdown)
but it wasn't removed from the doobie build as refined was bumped to
0.8.0.
=> Remove scala-compiler dependency from doobie-refined

modules/docs/src/main/tut/docs/15-Extensions-PostgreSQL.md
in .../doobie/postgres/Instances.scala:102 there are the uiid instances 
`implicit val (unliftedUUIDArrayType, liftedUUIDArrayType) = boxedPair[java.util.UUID] ("uuid", "_uuid")`.
=> Update docs about UUID array types

modules/postgres/src/main/scala/doobie/postgres/Text.scala
This seemed like the easiest way to stop pathological compilation times while being as close to what I can tell the expected functionality for inserting a Char to be i.e. should not differ from a string
=> add instance of Text[Char] fixing #826

CHANGELOG.md, build.sbt, modules/core/src/main/scala/doobie/aliases.scala, modules/core/src/main/scala/doobie/syntax/string.scala, modules/core/src/main/scala/doobie/util/ExecutionContexts.scala, modules/core/src/main/scala/doobie/util/fragment.scala, modules/core/src/main/scala/doobie/util/fragments.scala, modules/core/src/main/scala/doobie/util/param.scala, modules/core/src/main/scala/doobie/util/query.scala, modules/core/src/main/scala/doobie/util/update.scala, modules/core/src/test/scala/doobie/issue/780.scala, modules/core/src/test/scala/doobie/util/fragment.scala, modules/core/src/test/scala/doobie/util/param.scala, modules/h2/src/test/scala/doobie/h2/h2types.scala, modules/hikari/src/main/scala/doobie/hikari/HikariTransactor.scala, modules/postgres-circe/src/test/scala/doobie/postrges/circe/pgjsonspec.scala, modules/postgres/src/test/scala/doobie/postgres/pgtypes.scala
This makes `Fragment` composition stacksafe.
- Stack overflows occur when we compose `Fragment`s via combinators like `Fragments.in`. This happens because we rely on semigroupal composition of `Write` which isn't stacksafe.
- If instead `Fragment` maintained (conceptually) `elems: Chain[(A, Put[A]) forSome { type A}]` then we could compose fragments trivially by simple concatenation. We could then construct a stacksafe `Write[elems.type]` when it's time to turn the `Fragment` into a `Query`/`Update`. The singleton type gets buried and the user never sees it.
A consequence of this design is that it's no longer possible to turn a `Query`/`Update` back into a `Fragment`. I think this is probably ok.
=> stacksafe fragment (rebased for 0.7)

modules/core/src/main/scala/doobie/util/testing.scala, modules/specs2/src/test/scala/doobie/specs2/CheckerTests.scala
Closes #846
The change shouldn't break the existing code, since `TypeTag[A] <: WeakTypeTag[A]`.
=> Use weak type tags for Analyzable

modules/docs/src/main/tut/index.md
This switches from the deprecated Typelevel Code of Conduct to the newer Scala Code of Conduct.
=> Switch to Scala CoC

modules/quill/src/test/scala/doobie/quill/PostgresDoobieContextSpec.scala
For some reason I was qualifying `run` even though it was already in scope.
=> remove qualification

build.sbt, modules/core/src/main/scala/doobie/util/Colors.scala, modules/core/src/main/scala/doobie/util/ExecutionContexts.scala, modules/core/src/main/scala/doobie/util/testing.scala, modules/core/src/main/scala/doobie/util/transactor.scala, modules/core/src/main/scala/doobie/util/yolo.scala, modules/docs/src/main/resources/microsite/css/tweak.css, modules/docs/src/main/tut/docs/01-Introduction.md, modules/docs/src/main/tut/docs/03-Connecting.md, modules/docs/src/main/tut/docs/04-Selecting.md, modules/docs/src/main/tut/docs/05-Parameterized.md, modules/docs/src/main/tut/docs/06-Checking.md, modules/docs/src/main/tut/docs/07-Updating.md, modules/docs/src/main/tut/docs/08-Fragments.md, modules/docs/src/main/tut/docs/09-Error-Handling.md, modules/docs/src/main/tut/docs/10-Logging.md, modules/docs/src/main/tut/docs/11-Arrays.md, modules/docs/src/main/tut/docs/12-Custom-Mappings.md, modules/docs/src/main/tut/docs/13-Unit-Testing.md, modules/docs/src/main/tut/docs/14-Managing-Connections.md, modules/docs/src/main/tut/docs/15-Extensions-PostgreSQL.md, modules/docs/src/main/tut/docs/16-Extensions-H2.md, modules/docs/src/main/tut/docs/17-FAQ.md, modules/docs/src/main/tut/index.md, modules/docs/src/main/tut/infographic.md, modules/scalatest/src/main/scala/doobie/scalatest/AnalysisMatchers.scala, modules/scalatest/src/main/scala/doobie/scalatest/Checker.scala, project/plugins.sbt
This converts the docs from tut to mdoc and also parameterizes stuff on colorization and changes execution to be single-threaded so output shows up in time to be captured by mdoc.
=> convert docs from tut to mdoc

modules/docs/src/main/tut/docs/03-Connecting.md
After showing how to create a Monix `Task` `Transactor` the docs should show how to use that transactor rather than the `IO` one introduced earlier.
=> Fix typo in "Using Your Own Target Monad"

build.sbt, modules/hikari/src/test/scala/doobie/hikari/issue/824.scala
@unhappy-boi this testcase for #824 shows correct pool behavior, with connections being returned as transactions complete. Can you demonstrate your problem by modifying this testcase?
```
HikariTransactor should
Idle: 1, Active: 0, Total: 1, Waiting: 0
Idle: 0, Active: 10, Total: 10, Waiting: 16
...
dle: 0, Active: 10, Total: 10, Waiting: 16
Idle: 0, Active: 10, Total: 10, Waiting: 13
Idle: 0, Active: 10, Total: 10, Waiting: 13
Idle: 0, Active: 10, Total: 10, Waiting: 11
Idle: 0, Active: 10, Total: 10, Waiting: 11
Idle: 0, Active: 10, Total: 10, Waiting: 11
Idle: 0, Active: 10, Total: 10, Waiting: 11
Idle: 0, Active: 10, Total: 10, Waiting: 11
Idle: 0, Active: 10, Total: 10, Waiting: 11
Idle: 0, Active: 10, Total: 10, Waiting: 5
Idle: 0, Active: 10, Total: 10, Waiting: 5
Idle: 0, Active: …
```
=> Testcase for 824

.travis.yml, build.sbt, project/build.sbt
Like it says on the tin. Circe isn't available for 2.11 anymore so I'm dropping support here as well.
Note that Postgres JDBC driver 42.2.7 is out but I'm skipping it because the newly-added mapping from `inet` ⟷ `InetAddress` is buggy and the existing mapping via `PGObject` no longer works. There's a fix planned for 42.2.8 so I'll wait for that and try again.
=> update circe, fs2; remove 2.11 support

build.sbt
ci release was failing because of warnings during doc generation
=> allow warnings in doc generation

modules/core/src/main/scala/doobie/util/fragments.scala, modules/core/src/main/scala/doobie/util/query.scala, modules/core/src/main/scala/doobie/util/update.scala, modules/core/src/main/scala/doobie/util/write.scala, modules/core/src/test/scala/doobie/util/fragments.scala, modules/core/src/test/scala/doobie/util/query.scala
This re-enables:
- `Fragments.values(a)` to turn a value into a `?,?,...,?` fragment
- `Query/Query0/Update/Update0.toFragment`
Resolves #1023
=> Write → Fragment

modules/docs/src/main/tut/docs/01-Introduction.md
This commit fix a SQL command that's going to fail for most users.
If not specified the command will use $USER as the db default. Yet in
general the only present db is `postgres`.
=> tut: fix psql command

modules/docs/src/main/tut/docs/06-Checking.md
Fix for #1147 
It seemed that the first `.check` called the second `biggerThan`, so I just changed the second function's name (naming followed the pattern used for ` Country` and `Country2`)
=> Fix Typechecking Queries example's output

build.sbt
This is so we can get a doobie snapshot to go along with https://github.com/getquill/quill/issues/1996 … I guess we'll await 3.6.0 before tagging another doobie version ... ?
=> add quill snapshot

modules/core/src/main/scala/doobie/util/pretty.scala, modules/core/src/main/scala/doobie/util/testing.scala
I got an error `SQLFeatureNotSupportedException` in a test, but it got covered by NullPointerException. This commit should fix it.
=> fixes NullPointer if nested exception has null msg

project/build.sbt
This uses a `val` for the PostgreSQL version in `project/build.sbt` similar to how the version is [defined in the root `build.sbt`](https://github.com/tpolecat/doobie/blob/37416d8012f50cee28914c095a88b870437a25e8/build.sbt#L15) so that Scala Steward will update both versions at the same time. Recent updates only bumped the version in `build.sbt` (https://github.com/tpolecat/doobie/pull/1290) or in `project/build.sbt` (https://github.com/tpolecat/doobie/pull/1284).
=> Keep PostgreSQL versions in sync

modules/docs/src/main/mdoc/docs/04-Selecting.md, modules/docs/src/main/mdoc/docs/14-Managing-Connections.md
As reported in https://github.com/tpolecat/doobie/issues/1288, sub-lists are not being shown as expected in Doobie documentation. This is because when using paradox, [4 spaces or a tab of indentation are needed for sub-lists to be rendered as expected](https://github.com/lightbend/paradox/issues/452#issuecomment-711138155), but Doobie docs are using 2 spaces indentation for sub-lists.
This PR fixes that. I've build the docs locally and confirmed that the sub-lists now are shown as expected.
=> docs - use 4 spaces instead of 2 for sub-lists

.github/workflows/build.yml, .github/workflows/release.yml
Fixes
```
Error: Unable to process command '::add-path::/home/runner/bin' successfully.
Error: The `add-path` command is disabled.
```
=> update setup-scala GH action to v10

.github/workflows/build.yml, .github/workflows/release.yml, modules/free/src/main/scala/doobie/free/callablestatement.scala, modules/free/src/main/scala/doobie/free/connection.scala, modules/free/src/main/scala/doobie/free/databasemetadata.scala, modules/free/src/main/scala/doobie/free/kleisliinterpreter.scala, modules/free/src/main/scala/doobie/free/preparedstatement.scala, modules/free/src/main/scala/doobie/free/statement.scala
The dotty PR #1319 included generated code that used a newer JDK than 8, so this removes those operations. Also fixes Java 8 in CI.
=> oops, remove stuff from Java 9+ APIs

build.sbt
Due to idiocy a bunch of modules that should have been skipped weren't.
=> fix publish/skip

modules/docs/src/main/mdoc/docs/14-Managing-Connections.md
I think the sentence makes it sound like IOApp implements a ContextShift based off of ExecutionContext.global. Which is not the case: [PoolUtils.scala](https://github.com/typelevel/cats-effect/blob/8ae7479753d6673bf261e797c073bcfd54dd3050/core/jvm/src/main/scala/cats/effect/internals/PoolUtils.scala#L28)
Not sure if this new wording expresses the same what you initially intended to say, though.
=> docs: Clarify wording regarding ContextShift in IOApp

modules/docs/src/main/mdoc/index.md
The idea is to create the list of Adopters that use `doobie` in production, similar to what [Cats has in README](https://github.com/typelevel/cats/blob/master/README.md#adopters).
The motivation is to promote the library and make people feel more confident.
Thanks everyone!
=> Add Adopters list to documentation

modules/core/src/main/scala/doobie/util/fragment.scala
Many people have requested this. `Internals` doesn't respect monoidal structure but I doubt it will ever matter.
resolves #1384
=> expose fragment internals

build.sbt, modules/core/src/main/scala-2/util/GetPlatform.scala, modules/core/src/main/scala-2/util/PutPlatform.scala, modules/core/src/main/scala-2/util/ReadPlatform.scala, modules/core/src/main/scala-2/util/WritePlatform.scala, modules/core/src/main/scala-3.0.0-M2/util/ReadPlatform.scala, modules/core/src/main/scala-3.0.0-M2/util/WritePlatform.scala, modules/core/src/main/scala-3.0.0-M3/util/ReadPlatform.scala, modules/core/src/main/scala-3.0.0-M3/util/WritePlatform.scala, modules/core/src/main/scala/doobie/util/fragment.scala, modules/core/src/main/scala/doobie/util/read.scala, modules/core/src/main/scala/doobie/util/write.scala, modules/core/src/test/scala-2/doobie/util/GetSuitePlatform.scala, modules/core/src/test/scala-2/doobie/util/LogSuitePlatform.scala, modules/core/src/test/scala-2/doobie/util/PutSuitePlatform.scala, modules/core/src/test/scala-2/doobie/util/ReadSuitePlatform.scala, modules/core/src/test/scala-2/doobie/util/WriteSuitePlatform.scala, modules/core/src/test/scala-3/doobie/util/GetSuitePlatform.scala, modules/core/src/test/scala-3/doobie/util/PutSuitePlatform.scala, modules/core/src/test/scala/doobie/issue/780.scala, modules/core/src/test/scala/doobie/util/GetSuite.scala, modules/core/src/test/scala/doobie/util/PutSuite.scala, modules/core/src/test/scala/doobie/util/ReadSuite.scala, modules/docs/src/main/mdoc/docs/04-Selecting.md, modules/docs/src/main/mdoc/docs/18-FAQ.md, modules/example/src/main/scala-2/example/Orm.scala, modules/postgres/src/main/scala-2/doobie/postgres/TextPlatform.scala, modules/quill/src/main/scala/doobie/quill/DoobieContextBase.scala
This reverts PR #1353 which swapped out Shapeless for Magnolia. Lingering issues with unary products are blocking further development so I'm rolling this back for now. See discussions in #1343  and #1350 for context. 
Other simplifications introduced in #1343 prior to the Shapeless/Magnolia swap are also removed because one of the tests doesn't compile in 2.12, but I would consider a PR re-introducing them.
=> Revert magnolia

build.sbt
This is an interesting one.
Hikari depends on slf4j-api 1.7 according to the POM, unless you
take profiles into account, which apparently coursier does.
Hikari changes the slf4j-api dependency to 2.0-alphaN when
you are running Java 11 and above, this also is reflected when you
resolve using Coursier in Java 11 or Java 8.
The only reason to do this is to use Java module support.
Most Scala libraries do not care about Java Modules, so we can safely
ignore this.
Added a dependency to Hikari4, but adds an exclusion to slf4j-api.
Added a direct dependency to slf4j-api 1.7 to fullfill the contract.
=> Use HikariCP 4

modules/docs/src/main/mdoc/docs/14-Managing-Connections.md
Currently [Managing Connections page](https://tpolecat.github.io/doobie/docs/14-Managing-Connections.html#using-a-hikaricp-connection-pool) breaks after an empty code block. 
I've implemented this very complicated fix to resolve this issue.
=> Managing Connections page no longer breaks

modules/core/src/main/scala-3/util/ReadPlatform.scala, modules/core/src/main/scala-3/util/WritePlatform.scala, modules/core/src/test/scala-3/doobie/util/ReadSuitePlatform.scala, modules/core/src/test/scala-3/doobie/util/WriteSuitePlatform.scala, modules/postgres/src/main/scala-3/doobie/postgres/TextPlatform.scala, modules/postgres/src/test/scala-2/doobie/postgres/TextSuitePlatform.scala, modules/postgres/src/test/scala-3/postgres/TextSuitePlatform.scala
In order for this keyword to work, there needs to be a `derived` method available in the companion objects. This gives some of the `given`s the expected name.
This is what it looks like without this patch:
```
[error] -- [E008] Not Found Error: /home/.../doobie/modules/core/src/test/scala-3/doobie/util/ReadSuitePlatform.scala:25:51 
[error] 25 |    case class Foo(a: String, b: Int) derives util.Read
[error]    |                                                   ^
[error]    |value derived is not a member of object doobie.util.Read, but could be made available as an extension method.
[error]    |
[error]    |The following import might make progress towards fixing the problem:
[error]    |
[error]    |  import munit.Clue.generate
[error]    |
[error] one error found
```
=> Enable support for `derives` in Scala 3 for `Read`, `Write` and `Text`

modules/postgres/src/main/scala/doobie/postgres/syntax/FragmentSyntax.scala, modules/postgres/src/test/scala/doobie/postgres/Issue1512.scala
The challenge faced here was to capture the number of affected rows when ending a `COPY`.
To safely end a copy, it needs to be run in the finalizer of a `bracket`. We cannot retrieve values from a finalizer, so there was some logic in place to call `PFCI.endCopy` in two places and use `isActive` to determine if it should be called the second time. `isActive` seems to not be an `!isCopyEnded`, but rather "is connection reserved for this Copy operation?".
The fix is to replace the double closing with a reference
=> Fix effectful `copyIn` (Fixes #1512)

modules/postgres/src/main/scala/doobie/postgres/pgisinstances.scala, modules/postgres/src/test/scala/doobie/postgres/TypesSuite.scala
See #1264.
This PR adds both Get/Put implicits (doobie.postgres.PgisInstances) to allow conversions between Postgis Geography(Point) (coordinates as spherical) and Point types.
Surely additional conversions (POLYLINE, POLYGON...) are needed, It can be implemented in a similar way if this implementation is correct.
Here is an example that would be valid with this change:
```scala
/// CREATE TABLE countries(name TEXT PRIMARY KEY, location GEOGRAPHY(POINT, 4326));
case class Country(code: String, location: Option[Point])
def findCountry(n: String): ConnectionIO[Option[Country]] =
sql"select name, location from countries where name = $n".query[Country].option
```
=> Postgis: Add custom mapping for geography -> point postgres conversion

build.sbt, modules/docs/src/main/mdoc/docs/16-Extensions-H2.md, modules/h2-circe/src/main/scala/doobie/h2/circe/Instances.scala, modules/h2-circe/src/main/scala/doobie/h2/circe/json/json.scala, modules/h2-circe/src/test/scala/doobie/h2/circe/H2JsonSuite.scala
This PR introduces support for JSON type in H2.
Code and tests are based on Postgres implementation.
I've tried using native H2 type `ValueJson`, but H2 really insists on using VARCHAR/bytearray:
```scala
implicit val jsonPut: Put[Json] =
Put.Advanced.other[ValueJson](
NonEmptyList.of("JSON", "json")
).tcontramap(a =>
ValueJson.fromJson(a.noSpaces)
)
implicit val jsonGet: Get[Json] =
Get.Advanced.other[ValueJson](
NonEmptyList.of("JSON", "json")
).temap(a =>
parse(a.getString).leftMap(_.show)
)
```
=> Add support for JSON in H2 using circe

.github/workflows/ci.yml, build.sbt, modules/core/src/test/scala/doobie/util/StrategySuite.scala, modules/free/src/main/scala/doobie/free/callablestatement.scala, modules/free/src/main/scala/doobie/free/connection.scala, modules/free/src/main/scala/doobie/free/databasemetadata.scala, modules/free/src/main/scala/doobie/free/kleisliinterpreter.scala, modules/free/src/main/scala/doobie/free/preparedstatement.scala, modules/free/src/main/scala/doobie/free/statement.scala, modules/postgres/src/main/scala/doobie/postgres/free/kleisliinterpreter.scala, modules/postgres/src/main/scala/doobie/postgres/free/pgconnection.scala, modules/postgres/src/test/scala/doobie/postgres/CheckSuite.scala
Somehow [this commit](https://github.com/tpolecat/doobie/commit/3231e7928e7eee5a4a91b32d7bdc2836381d1f0e) got dropped and we ended up with JDK9+ JDBC stuff in here. This removes it and pushes the CI version back to 8.
=> remove jdk9+ stuff

modules/docs/src/main/mdoc/docs/15-Extensions-PostgreSQL.md, modules/postgres/src/main/scala/doobie/postgres/package.scala, modules/postgres/src/main/scala/doobie/postgres/pgisgeographyinstances.scala, modules/postgres/src/test/scala/doobie/postgres/TypesSuite.scala
See #1264.
Previous reverted PR #1625 overrides default postgis PointType implicit conversion by mistake.
This PR adds both pgisgeographyimplicits conversions to use geomtries backed by geodetic coordinataes (postgis geography).
Here is an example that would be valid with this change:
/// CREATE TABLE countries(name TEXT PRIMARY KEY, location GEOGRAPHY(POINT, 4326));
case class Country(code: String, location: Option[Point])
def findCountry(n: String): ConnectionIO[Option[Country]] =
sql"select name, location from countries where name = $n".query[Country].option
=> define pgisgeographyinstances for geography postgis types

modules/core/src/main/scala/doobie/free/Aliases.scala, modules/core/src/test/scala/doobie/util/ConnectionIOSuite.scala, modules/free/src/main/scala/doobie/free/connection.scala
Using this quite a lot to combine affected rows, but also upon retrieval of stuff to combine sets together.
I've found there is a generic way to express this:
```scala
implicit final def semigroupF[A](implicit A: Semigroup[A], F: Apply[F]): Semigroup[F[A]] =
Apply.semigroup[F, A]
```
It's however not standard in cats, and I think it would fit here well?
Any suggestions welcome!
=> Add Monoid and Semigroup instances for ConnectionIO

modules/hikari/src/main/scala/doobie/hikari/Config.scala, modules/hikari/src/main/scala/doobie/hikari/HikariTransactor.scala, modules/hikari/src/test/scala/doobie/hikari/ConfigSpec.scala
These new methods provide good default behavior. Using these makes it difficult to shoot oneself to own foot by passing in a wrong EC.
=> Add functions for creating HikariTransactor that automatically create connectEC

modules/core/src/main/scala/doobie/util/transactor.scala, modules/hikari/src/main/scala/doobie/hikari/Config.scala, modules/hikari/src/main/scala/doobie/hikari/HikariTransactor.scala, modules/hikari/src/test/scala/doobie/hikari/ConfigSpec.scala
Technically a breaking change, but very small and it's worth the simplification and we're still before 1.0.0 proper :crossed_fingers:
=> Refactor Hikari config

modules/docs/src/main/mdoc/docs/15-Extensions-PostgreSQL.md
I recently had a problem in one of my codebases where the Java 8 and PostgreSQL date/time types had misaligned which resulted in the BST timezone being used when we wanted GMT/UTC. When resolving my problem I found this useful info in the [javadocs](https://github.com/tpolecat/doobie/blob/d99ba2ba9fedf4b0869ac4e6feb3bb49269f11fd/modules/postgres/src/main/scala/doobie/postgres/JavaTimeInstances.scala) and thought it would be very useful to have it also documented in the microsite docs.
I also modified the import required given that these docs are in the PostgreSQL extension section, which provides support for the full list of Java 8 time types supported by the Doobie PostgreSQL extension.
=> Add detail to docs for Java 8 time types

modules/core/src/main/scala/doobie/util/analysis.scala, modules/postgres/src/main/scala/doobie/postgres/JavaTimeInstances.scala, modules/postgres/src/test/scala/doobie/postgres/CheckSuite.scala, modules/postgres/src/test/scala/doobie/postgres/TypesSuite.scala
Given that the Postgres JDBC driver does not return *WithTimezone types,
change the type when creating meta column and parameter objects. This
allows the Java time instance for `OffsetDateTime` to be defined as
requiring a column to be a `TimestampWithTimezone`.
=> Better Java time instances for PostgreSQL

modules/core/src/main/scala-3/util/ReadPlatform.scala
There seems to be a bug where using by-name parameter in deriving will lead to Scala 3 compiler thinking that an instance of Read[T] exist (even though it doesn't), which leads to NPEs when it's used.
Removing the by-name should be safe, as Read only works with products and won't need to worry about recursive definitions.
Fixes #1808
=> Fix NPE in Scala 3 derivation

.github/workflows/ci.yml, build.sbt, modules/free/src/main/scala/doobie/free/blob.scala, modules/free/src/main/scala/doobie/free/callablestatement.scala, modules/free/src/main/scala/doobie/free/clob.scala, modules/free/src/main/scala/doobie/free/connection.scala, modules/free/src/main/scala/doobie/free/databasemetadata.scala, modules/free/src/main/scala/doobie/free/driver.scala, modules/free/src/main/scala/doobie/free/kleisliinterpreter.scala, modules/free/src/main/scala/doobie/free/nclob.scala, modules/free/src/main/scala/doobie/free/preparedstatement.scala, modules/free/src/main/scala/doobie/free/ref.scala, modules/free/src/main/scala/doobie/free/resultset.scala, modules/free/src/main/scala/doobie/free/sqldata.scala, modules/free/src/main/scala/doobie/free/sqlinput.scala, modules/free/src/main/scala/doobie/free/sqloutput.scala, modules/free/src/main/scala/doobie/free/statement.scala, modules/postgres/src/main/scala/doobie/postgres/free/copyin.scala, modules/postgres/src/main/scala/doobie/postgres/free/copymanager.scala, modules/postgres/src/main/scala/doobie/postgres/free/copyout.scala, modules/postgres/src/main/scala/doobie/postgres/free/kleisliinterpreter.scala, modules/postgres/src/main/scala/doobie/postgres/free/largeobject.scala, modules/postgres/src/main/scala/doobie/postgres/free/largeobjectmanager.scala, modules/postgres/src/main/scala/doobie/postgres/free/pgconnection.scala, project/FreeGen2.scala
- compile command will now always run freegen2 first
- Allow listing classes to exclude from imports in the generated kleisliinterpreter.scala file to avoid unused import warning
- Add check in CI and fail if there are diffs
=> Resynchonize Freegen2 code generation

modules/core/src/main/scala/doobie/util/fragments.scala, modules/core/src/test/scala/doobie/util/FragmentsSuite.scala
- all andOpt/orOpt calls that can lead to zero input fragments (e.g. empty list or all None var args) will now return None. This makes it compose better
- Revert and/or to only take Reducible collections
- Surrounds and/or expressions with parenthesis
Fixes #1850
=> Rework fragment helpers

build.sbt, modules/core/src/main/scala-3/util/WritePlatform.scala, modules/core/src/main/scala/doobie/util/write.scala, modules/core/src/test/scala-3/doobie/util/ReadSuitePlatform.scala, modules/core/src/test/scala-3/doobie/util/WriteSuitePlatform.scala
#1816 fixed NPE for Read instances, but bug persisted for Write instances.
@jatcwang mentioned that recursive definitions for Read do not exist, if that's also the case for Write we can make the same change as in #1816 but for Write.
5d52836 commit introduces test that succeeds for Read, but fails for Write. Next commit introduces the mentioned change that makes the Write test also pass.
=> Fix NPE in Scala 3 derivation for Write

.github/workflows/ci.yml, .mergify.yml, build.sbt, modules/log4cats/src/main/scala/doobie/log4cats/Log4CatsDebuggingLogHandler.scala, modules/log4cats/src/main/scala/doobie/log4cats/Log4CatsLogHandler.scala
Creates the `Log4CatsDebuggingLogHandler` class
=> Add module for log4cats support for debugging purposes

modules/free/src/main/scala/doobie/WeakAsync.scala
Really interesting brainstorm with @TimWSpence. We can avoid the overhead of submitting to `Dispatcher`, starting a fiber, creating an async boundary, etc. by first attempting to `syncStep` i.e. interpret `F[_]` directly into `G[_]`. If the given effect is only using `Sync` ops then it can be interpreted to entirety without needing the `Dispatcher`. If not, the `Dispatcher` serves as a fallback.
=> Use `syncStep` in `WeakAsync.liftK`

modules/free/src/main/scala/doobie/WeakAsync.scala
So that we can specifically get a `LiftIO`. h/t @henricook for the idea.
=> Add `WeakAsync.liftIO`

modules/core/src/main/scala/doobie/util/fragments.scala, modules/core/src/test/scala/doobie/util/FragmentsSuite.scala
=> Fix fragment helpers to handle fragments without spaces at the end (i.e. fr0, sql interpolator)

modules/docs/src/main/mdoc/docs/15-Extensions-PostgreSQL.md
Thanks for not adding a redirect, postgres folks. Really appreciate that
=> Fix link rot in postgres docs

modules/docs/src/main/mdoc/docs/13-Unit-Testing.md, modules/example/src/main/scala/example/PostgresNotify.scala
A minor typo that I saw in the docs, I thought it would be helpful to open a PR for it.
=> Fix typo transcator -> transactor

modules/docs/src/main/mdoc/docs/15-Extensions-PostgreSQL.md
As of 1.0-RC3 the ZDT implicit is gone because it's never been correct with the actual data stored.
=> Remove reference to ZonedDateTime in pgsql docs

modules/docs/src/main/mdoc/docs/14-Managing-Connections.md, modules/hikari/src/main/scala/doobie/hikari/HikariTransactor.scala
/cc @piton4k
closes https://github.com/tpolecat/doobie/issues/1902
=> Allow for different effects of HikariTransactor and its creation

modules/docs/src/main/mdoc/docs/14-Managing-Connections.md, modules/hikari/src/main/scala/doobie/hikari/HikariTransactor.scala
Partially revert the change in #1939 so that existing code don't fail to compile. Methods which construct HikariTransactor in a different effect now has the suffix "...SeparateEffect". The original single-effect methods are now implemented in terms of the separate-effect methods.
Related: #1939
=> Split methods for HikariTransactor constructed with two effects

.github/workflows/ci.yml, .mergify.yml, build.sbt, modules/mysql/src/main/scala/doobie/mysql/MysqlJavaTimeInstances.scala, modules/mysql/src/main/scala/doobie/mysql/package.scala, modules/mysql/src/test/scala/doobie/mysql/CheckSuite.scala, modules/mysql/src/test/scala/doobie/mysql/MySQLTestTransactor.scala, modules/mysql/src/test/scala/doobie/mysql/TypesSuite.scala, modules/mysql/src/test/scala/doobie/mysql/util/arbitraries/SQLArbitraries.scala, modules/mysql/src/test/scala/doobie/mysql/util/arbitraries/TimeArbitraries.scala
Note that unlike PostgreSQL, MySQL TIMESTAMP columns (vendor type TIMESTAMP) are semantically used to store java.time.Instant.
Reference: https://dev.mysql.com/doc/connector-j/en/connector-j-time-instants.html
=> Add MySQL java.time instances

.github/workflows/ci.yml, build.sbt, modules/core/src/main/scala-2/util/ReadPlatform.scala, modules/core/src/main/scala-2/util/WritePlatform.scala, modules/core/src/main/scala-3/util/ReadPlatform.scala, modules/core/src/main/scala-3/util/WritePlatform.scala, modules/core/src/main/scala/doobie/util/package.scala, modules/core/src/main/scala/doobie/util/read.scala, modules/core/src/main/scala/doobie/util/write.scala, modules/core/src/test/scala-2/doobie/util/ReadSuitePlatform.scala, modules/core/src/test/scala/doobie/util/ReadSuite.scala, modules/core/src/test/scala/doobie/util/TestTypes.scala, modules/core/src/test/scala/doobie/util/WriteSuite.scala, modules/postgres/src/main/scala/doobie/postgres/package.scala
Remove instances for HNil / EmptyTuple (alone), as this causes auto-derivation of Read/Write instances for _any_ case object which leads to incorrect SQL being generated.
The fix is to change the base case to product 1s (A :: HNil, or A *: EmptyTuple in Scala 3)
- Add more round-trip tests to fully test the logic
- Align names of derivation methods
Fixes #1991
=> Fix instance derivation

modules/core/src/main/scala/doobie/util/fragments.scala, modules/core/src/test/scala/doobie/util/FragmentsSuite.scala
This avoids expressions from "leaking" and changing the overall semantics e.g. `and(fr"expr1", fr"expr2 OR expr3")` should be equivalent to `(expr1) AND (expr2 OR expr3)` not `expr1 AND expr2 OR expr3`
=> Add parenthesis around each expression in and/or combinator

modules/core/src/main/scala/doobie/free/Aliases.scala, modules/core/src/main/scala/doobie/hi/Aliases.scala, modules/core/src/main/scala/doobie/hi/connection.scala, modules/core/src/main/scala/doobie/hi/preparedstatement.scala, modules/core/src/main/scala/doobie/hi/resultset.scala, modules/core/src/main/scala/doobie/hi/statement.scala, modules/core/src/main/scala/doobie/syntax/connectionio.scala, modules/core/src/main/scala/doobie/util/fragment.scala, modules/core/src/main/scala/doobie/util/query.scala, modules/core/src/main/scala/doobie/util/read.scala, modules/core/src/main/scala/doobie/util/transactor.scala, modules/core/src/main/scala/doobie/util/update.scala, modules/core/src/main/scala/doobie/util/write.scala, modules/core/src/test/scala/doobie/util/TestTypes.scala, modules/postgres/src/main/scala/doobie/postgres/free/aliases.scala, modules/postgres/src/main/scala/doobie/postgres/hi/aliases.scala, modules/postgres/src/main/scala/doobie/postgres/hi/connection.scala, modules/postgres/src/main/scala/doobie/postgres/hi/largeobject.scala, modules/postgres/src/main/scala/doobie/postgres/hi/largeobjectmanager.scala, modules/postgres/src/main/scala/doobie/postgres/hi/lostreaming.scala, modules/postgres/src/main/scala/doobie/postgres/hi/pgconnection.scala, modules/postgres/src/main/scala/doobie/postgres/rangeinstances.scala, modules/postgres/src/main/scala/doobie/postgres/syntax/FragmentSyntax.scala
This would ocassionally cause deadlocks which is hard to debug. Fixes #1369.
Inside doobie itself we cannot use aliases like `doobie.free.FC` because it'll lead to cyclic dependencies during class loading. Therefore this PR switches all existing alias use to an import alias to e.g. `doobie.free.{connection => IFC}` (I stands for internal)
=> Remove lazy initialization of modules

.github/workflows/ci.yml, build.sbt, modules/core/src/main/scala/doobie/hi/connection.scala, modules/core/src/test/scala/doobie/util/QueryLogSuite.scala, modules/core/src/test/scala/doobie/util/UpdateLogSuite.scala, modules/free/src/main/scala/doobie/WeakAsync.scala, modules/free/src/main/scala/doobie/free/blob.scala, modules/free/src/main/scala/doobie/free/callablestatement.scala, modules/free/src/main/scala/doobie/free/clob.scala, modules/free/src/main/scala/doobie/free/connection.scala, modules/free/src/main/scala/doobie/free/databasemetadata.scala, modules/free/src/main/scala/doobie/free/driver.scala, modules/free/src/main/scala/doobie/free/kleisliinterpreter.scala, modules/free/src/main/scala/doobie/free/nclob.scala, modules/free/src/main/scala/doobie/free/preparedstatement.scala, modules/free/src/main/scala/doobie/free/ref.scala, modules/free/src/main/scala/doobie/free/resultset.scala, modules/free/src/main/scala/doobie/free/sqldata.scala, modules/free/src/main/scala/doobie/free/sqlinput.scala, modules/free/src/main/scala/doobie/free/sqloutput.scala, modules/free/src/main/scala/doobie/free/statement.scala, modules/hikari/src/test/scala/doobie/HikariQueryCancellationSuite.scala, modules/postgres/src/main/scala/doobie/postgres/free/copyin.scala, modules/postgres/src/main/scala/doobie/postgres/free/copymanager.scala, modules/postgres/src/main/scala/doobie/postgres/free/copyout.scala, modules/postgres/src/main/scala/doobie/postgres/free/kleisliinterpreter.scala, modules/postgres/src/main/scala/doobie/postgres/free/largeobject.scala, modules/postgres/src/main/scala/doobie/postgres/free/largeobjectmanager.scala, modules/postgres/src/main/scala/doobie/postgres/free/pgconnection.scala, project/FreeGen2.scala
Alternative fix of problem described here https://github.com/tpolecat/doobie/pull/2077
=> fix query cancellation with cancelable

modules/core/src/main/scala/doobie/hi/connection.scala, modules/hikari/src/test/scala/doobie/HikariQueryCancellationSuite.scala
`Stream.bracket` does not allow cancellation in the `acquire` step which is why we're using `bracketFull` instead
=> Query cancellation for streaming queries

README.md, modules/docs/src/main/mdoc/docs/12-Custom-Mappings.md, modules/hikari/src/main/scala/doobie/hikari/HikariTransactor.scala
I noticed that links in the README.md stopped working. Once I saw the discussion about moving the repository into the typelevel org, I figured out why. I replaced the old link with `https://typelevel.org/doobie/`. Since it would be more annoying to open an issue than it was to fix this, I created this PR straight away. If this is not okay then feel free to ignore it and sorry for the trouble.
=> Update microsite link

modules/core/src/main/scala/doobie/util/fragments.scala, modules/core/src/test/scala/doobie/util/FragmentsSuite.scala
This tries to solve #1893.
I hope the tests run through, as I could not successfully run all tests locally. At some point the testsuite just hanged on my Apple M1. Also, locally, I needed to switch the mysql docker image in the docker compose file to work on the M1.
=> Introduce `updateSetOpt` fragment (#1893)

modules/core/src/main/scala/doobie/util/fragments.scala, modules/core/src/test/scala/doobie/util/FragmentsSuite.scala
Current `in`, `notIn`, `inOpt`, etc fragment builders only allow 1 or 2 values per matching row.
The proposed builders take `Read` instead of `Get` and therefore allow products of any arity.
Moreover, the current 2-arity builders accept values packed as `Tuple2` only. The proposed builders accept tuples as well as case classes, which can come in handy in some cases.
In fact, neither the existing nor the proposed builders allow to build full-featured `IN`/`NOT IN` expression. Both allow just a subset of features – matching against a static set of values. Besides, we cannot have `in` function overloads for both kinds of builders. Therefore, if we want to keep the existing builders, we'll have to choose another names for the new ones.
Names `inValues` and `notInValues` look pretty …
=> Proposal: `IN` and `NOT IN` fragment builders for product types with arbitrary arities

modules/core/src/main/scala/doobie/syntax/stream.scala, modules/example/src/main/scala/example/StreamingCopy.scala, modules/hikari/src/test/scala/doobie/postgres/StreamPrefetchSuite.scala
Resolves https://github.com/typelevel/doobie/issues/2132.
Use fs2 Stream's `prefetchN` to buffer query results so that slow downstream operations don't slow down transaction commit.
The buffered result size is `chunkSize` (equals to `fetchSize`) by default. If want a different buffer size, can use `transactNoPrefetc` to get a stream without `prefetchN` and append any prefetch operations wanted.
=> Prefetch a chunk of result for stream operation

modules/core/src/main/scala/doobie/util/put.scala, modules/core/src/test/scala/doobie/util/WriteSuite.scala
Same as #2141 but in the simplest possible manner.
=> Make null param error more informative (#809)

.github/workflows/ci.yml, build.sbt, modules/docs/src/main/mdoc/docs/15-Extensions-PostgreSQL.md, modules/docs/src/main/mdoc/docs/17-FAQ.md
=> Fix docs and check makeSite passes in CI

init/postgres/test-db.sql, modules/core/src/main/scala/doobie/util/meta/meta.scala, modules/docs/src/main/mdoc/docs/11-Arrays.md, modules/postgres/src/main/scala/doobie/postgres/Instances.scala, modules/postgres/src/test/scala/doobie/postgres/PgArraySuite.scala, modules/postgres/src/test/scala/doobie/postgres/enums/MyEnum.scala, modules/postgres/src/test/scala/doobie/postgres/enums/OtherEnum.scala
Add a helper `doobie.postgres.implicits.arrayOfEnum` with better typechecking support.
For an array column, postgres prefixes `_` in front of the type name, therefore the expected vendor type name is e.g. `_myenum`
Also added some tests / examples to test array of enum where the enum is defined in another schema. (e.g. Reported vendor type name is `"other_schema"."_other_enum"` for the column type `other_schema.other_enum[]`)
Fixes #2107 #2127
=> Better postgres array of enum support

modules/core/src/main/scala/doobie/util/fragment.scala, modules/core/src/test/scala/doobie/util/FragmentSuite.scala, modules/docs/src/main/mdoc/docs/08-Fragments.md
This PR proposes a new operator `+~+` for fragments concatenation that makes sure that there is at least 1 whitespace between the fragments being concatenated. I realize, this proposal is going to be a controversial one. However I decided to give it a shot.
I've been working with Doobie for quite a while and use its fragment API to create pretty sophisticated queries. Some of those queries are created dynamically, i.e. various parts of the SQL are concatenated depending on some external conditions. With time I started getting a feeling that the whole `fr`/`fr0`/`const`/`const0` paradigm might not be the great idea at all. When I create a fragment that may or may not be concatenated with something else later, I don't really want to worry about whether I have to end it with a whitespace or …
=> Propose a fragment concat operator that ensures a whitespace in between

modules/postgres/src/test/scala/doobie/postgres/NotifySuite.scala
I have successfully migrated all the tests, and they are now failing for incorrect values as well. This confirms that the migration is working as intended and performing correctly, which was the primary objective.
=> Migrated NotifySuite tests

build.sbt, modules/mysql/src/main/scala/doobie/mysql/MysqlJavaTimeInstances.scala, modules/mysql/src/test/scala/doobie/mysql/MySQLTestTransactor.scala
This includes several minor fixes: fixing dead links to the article on the Oracle docs site and resolving a warning in the SBT shell.
=> Fix dead link to the 'Preserving Time Instants' article

build.sbt
https://docs.scala-lang.org/scala3/guides/migration/tooling-scala2-xsource3.html
=> add `-Xsource:3-cross` option if Scala 2.13
